name: headlamp
region: sfo3
services:
- name: backend
  dockerfile_path: Dockerfile
  source_dir: .
  github:
    branch: main
    deploy_on_push: true
    repo: The-You-School-HeadLamp/headlamp_backend
  http_port: 8080
  instance_count: 1
  instance_size_slug: professional-l
  routes:
  - path: /
databases:
- name: postgres-db
  engine: PG
  version: "17"
  size: db-s-1vcpu-1gb

