// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: accessible_social_media.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllSocialMediaPlatforms = `-- name: GetAllSocialMediaPlatforms :many
SELECT id, name, icon_url FROM social_medias
`

func (q *Queries) GetAllSocialMediaPlatforms(ctx context.Context) ([]SocialMedia, error) {
	rows, err := q.db.Query(ctx, getAllSocialMediaPlatforms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SocialMedia{}
	for rows.Next() {
		var i SocialMedia
		if err := rows.Scan(&i.ID, &i.Name, &i.IconUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSocialMediaAccessRule = `-- name: GetSocialMediaAccessRule :one
SELECT id, child_id, social_media_id, is_accessible, access_revoked_at, session_duration_seconds FROM accessible_social_media
WHERE child_id = $1 AND social_media_id = $2
LIMIT 1
`

type GetSocialMediaAccessRuleParams struct {
	ChildID       string `json:"child_id"`
	SocialMediaID int64  `json:"social_media_id"`
}

func (q *Queries) GetSocialMediaAccessRule(ctx context.Context, arg GetSocialMediaAccessRuleParams) (AccessibleSocialMedium, error) {
	row := q.db.QueryRow(ctx, getSocialMediaAccessRule, arg.ChildID, arg.SocialMediaID)
	var i AccessibleSocialMedium
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.SocialMediaID,
		&i.IsAccessible,
		&i.AccessRevokedAt,
		&i.SessionDurationSeconds,
	)
	return i, err
}

const getSocialMediaAccessSettingsForParent = `-- name: GetSocialMediaAccessSettingsForParent :many
SELECT
  sm.id AS social_media_id,
  sm.name,
  sm.icon_url,
  COALESCE(asm.is_accessible, false) AS is_accessible,
  COALESCE(asm.session_duration_seconds, 3600) AS session_duration_seconds
FROM social_medias sm
LEFT JOIN accessible_social_media asm
  ON sm.id = asm.social_media_id AND asm.child_id = $1
ORDER BY sm.name
`

type GetSocialMediaAccessSettingsForParentRow struct {
	SocialMediaID          int64       `json:"social_media_id"`
	Name                   string      `json:"name"`
	IconUrl                pgtype.Text `json:"icon_url"`
	IsAccessible           bool        `json:"is_accessible"`
	SessionDurationSeconds int32       `json:"session_duration_seconds"`
}

func (q *Queries) GetSocialMediaAccessSettingsForParent(ctx context.Context, childID string) ([]GetSocialMediaAccessSettingsForParentRow, error) {
	rows, err := q.db.Query(ctx, getSocialMediaAccessSettingsForParent, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSocialMediaAccessSettingsForParentRow{}
	for rows.Next() {
		var i GetSocialMediaAccessSettingsForParentRow
		if err := rows.Scan(
			&i.SocialMediaID,
			&i.Name,
			&i.IconUrl,
			&i.IsAccessible,
			&i.SessionDurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSocialMediaAccessStatusForChild = `-- name: GetSocialMediaAccessStatusForChild :many
SELECT
  sm.id AS social_media_id,
  sm.name,
  sm.icon_url,
  COALESCE(asm.is_accessible, false) AS is_accessible
FROM social_medias sm
LEFT JOIN accessible_social_media asm
  ON sm.id = asm.social_media_id AND asm.child_id = $1
`

type GetSocialMediaAccessStatusForChildRow struct {
	SocialMediaID int64       `json:"social_media_id"`
	Name          string      `json:"name"`
	IconUrl       pgtype.Text `json:"icon_url"`
	IsAccessible  bool        `json:"is_accessible"`
}

func (q *Queries) GetSocialMediaAccessStatusForChild(ctx context.Context, childID string) ([]GetSocialMediaAccessStatusForChildRow, error) {
	rows, err := q.db.Query(ctx, getSocialMediaAccessStatusForChild, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSocialMediaAccessStatusForChildRow{}
	for rows.Next() {
		var i GetSocialMediaAccessStatusForChildRow
		if err := rows.Scan(
			&i.SocialMediaID,
			&i.Name,
			&i.IconUrl,
			&i.IsAccessible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSocialMediaAccess = `-- name: SetSocialMediaAccess :one
INSERT INTO accessible_social_media (
  child_id,
  social_media_id,
  is_accessible,
  session_duration_seconds
) VALUES (
  $1, $2, $3, $4
) ON CONFLICT (child_id, social_media_id) DO UPDATE SET
  is_accessible = EXCLUDED.is_accessible,
  session_duration_seconds = EXCLUDED.session_duration_seconds,
  access_revoked_at = CASE WHEN EXCLUDED.is_accessible = false THEN now() ELSE NULL END
RETURNING id, child_id, social_media_id, is_accessible, access_revoked_at, session_duration_seconds
`

type SetSocialMediaAccessParams struct {
	ChildID                string `json:"child_id"`
	SocialMediaID          int64  `json:"social_media_id"`
	IsAccessible           bool   `json:"is_accessible"`
	SessionDurationSeconds int32  `json:"session_duration_seconds"`
}

func (q *Queries) SetSocialMediaAccess(ctx context.Context, arg SetSocialMediaAccessParams) (AccessibleSocialMedium, error) {
	row := q.db.QueryRow(ctx, setSocialMediaAccess,
		arg.ChildID,
		arg.SocialMediaID,
		arg.IsAccessible,
		arg.SessionDurationSeconds,
	)
	var i AccessibleSocialMedium
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.SocialMediaID,
		&i.IsAccessible,
		&i.AccessRevokedAt,
		&i.SessionDurationSeconds,
	)
	return i, err
}
