// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWeeklyUsageSummary = `-- name: GetWeeklyUsageSummary :many
SELECT
    sm.id AS social_media_id,
    sm.name AS social_media_name,
    sm.icon_url AS social_media_logo,
    CAST(DATE_TRUNC('day', s.start_time AT TIME ZONE 'UTC') AS TIMESTAMPTZ) AS usage_day,
    CAST(SUM(EXTRACT(EPOCH FROM (LEAST(s.end_time, NOW()) - s.start_time))) / 60 AS float8) AS total_minutes
FROM
    app_sessions s
JOIN
    social_medias sm ON s.social_media_id = sm.id
WHERE
    s.child_id = $1
    AND s.start_time >= (NOW() - INTERVAL '7 days')
GROUP BY
    sm.id, sm.name, sm.icon_url, usage_day
ORDER BY
    sm.id, usage_day
`

type GetWeeklyUsageSummaryRow struct {
	SocialMediaID   int64       `json:"social_media_id"`
	SocialMediaName string      `json:"social_media_name"`
	SocialMediaLogo pgtype.Text `json:"social_media_logo"`
	UsageDay        time.Time   `json:"usage_day"`
	TotalMinutes    float64     `json:"total_minutes"`
}

func (q *Queries) GetWeeklyUsageSummary(ctx context.Context, childID string) ([]GetWeeklyUsageSummaryRow, error) {
	rows, err := q.db.Query(ctx, getWeeklyUsageSummary, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWeeklyUsageSummaryRow{}
	for rows.Next() {
		var i GetWeeklyUsageSummaryRow
		if err := rows.Scan(
			&i.SocialMediaID,
			&i.SocialMediaName,
			&i.SocialMediaLogo,
			&i.UsageDay,
			&i.TotalMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
