// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_session.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeSessionsForChild = `-- name: CloseSessionsForChild :many
UPDATE app_sessions
SET end_time = last_ping_time
WHERE child_id = $1 AND end_time IS NULL
RETURNING id, child_id, social_media_id, start_time, end_time, expected_end_time, status, created_at, updated_at, last_ping_time
`

func (q *Queries) CloseSessionsForChild(ctx context.Context, childID string) ([]AppSession, error) {
	rows, err := q.db.Query(ctx, closeSessionsForChild, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSession{}
	for rows.Next() {
		var i AppSession
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.SocialMediaID,
			&i.StartTime,
			&i.EndTime,
			&i.ExpectedEndTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastPingTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeStaleSessions = `-- name: CloseStaleSessions :many
UPDATE app_sessions
SET end_time = last_ping_time
WHERE end_time IS NULL AND last_ping_time < NOW() - INTERVAL '5 minutes'
RETURNING id, child_id, social_media_id, start_time, end_time, expected_end_time, status, created_at, updated_at, last_ping_time
`

func (q *Queries) CloseStaleSessions(ctx context.Context) ([]AppSession, error) {
	rows, err := q.db.Query(ctx, closeStaleSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSession{}
	for rows.Next() {
		var i AppSession
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.SocialMediaID,
			&i.StartTime,
			&i.EndTime,
			&i.ExpectedEndTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastPingTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAppSession = `-- name: CreateAppSession :one
INSERT INTO app_sessions (
    child_id,
    social_media_id,
    start_time,
    expected_end_time
) VALUES (
    $1, $2, $3, $4
) RETURNING id, child_id, social_media_id, start_time, end_time, expected_end_time, status, created_at, updated_at, last_ping_time
`

type CreateAppSessionParams struct {
	ChildID         string    `json:"child_id"`
	SocialMediaID   int64     `json:"social_media_id"`
	StartTime       time.Time `json:"start_time"`
	ExpectedEndTime time.Time `json:"expected_end_time"`
}

func (q *Queries) CreateAppSession(ctx context.Context, arg CreateAppSessionParams) (AppSession, error) {
	row := q.db.QueryRow(ctx, createAppSession,
		arg.ChildID,
		arg.SocialMediaID,
		arg.StartTime,
		arg.ExpectedEndTime,
	)
	var i AppSession
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.SocialMediaID,
		&i.StartTime,
		&i.EndTime,
		&i.ExpectedEndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPingTime,
	)
	return i, err
}

const endAppSession = `-- name: EndAppSession :one
UPDATE app_sessions
SET
    end_time = $2,
    status = 'closed',
    updated_at = NOW()
WHERE
    id = $1 AND child_id = $3
RETURNING id, child_id, social_media_id, start_time, end_time, expected_end_time, status, created_at, updated_at, last_ping_time
`

type EndAppSessionParams struct {
	ID      uuid.UUID          `json:"id"`
	EndTime pgtype.Timestamptz `json:"end_time"`
	ChildID string             `json:"child_id"`
}

func (q *Queries) EndAppSession(ctx context.Context, arg EndAppSessionParams) (AppSession, error) {
	row := q.db.QueryRow(ctx, endAppSession, arg.ID, arg.EndTime, arg.ChildID)
	var i AppSession
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.SocialMediaID,
		&i.StartTime,
		&i.EndTime,
		&i.ExpectedEndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPingTime,
	)
	return i, err
}

const getActiveAppSession = `-- name: GetActiveAppSession :one
SELECT id, child_id, social_media_id, start_time, end_time, expected_end_time, status, created_at, updated_at, last_ping_time FROM app_sessions
WHERE child_id = $1 AND social_media_id = $2 AND end_time IS NULL
ORDER BY start_time DESC
LIMIT 1
`

type GetActiveAppSessionParams struct {
	ChildID       string `json:"child_id"`
	SocialMediaID int64  `json:"social_media_id"`
}

func (q *Queries) GetActiveAppSession(ctx context.Context, arg GetActiveAppSessionParams) (AppSession, error) {
	row := q.db.QueryRow(ctx, getActiveAppSession, arg.ChildID, arg.SocialMediaID)
	var i AppSession
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.SocialMediaID,
		&i.StartTime,
		&i.EndTime,
		&i.ExpectedEndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPingTime,
	)
	return i, err
}

const getActiveSessionForChild = `-- name: GetActiveSessionForChild :one
SELECT id, child_id, social_media_id, start_time, end_time, expected_end_time, status, created_at, updated_at, last_ping_time FROM app_sessions
WHERE child_id = $1 AND end_time IS NULL
ORDER BY start_time DESC
LIMIT 1
`

func (q *Queries) GetActiveSessionForChild(ctx context.Context, childID string) (AppSession, error) {
	row := q.db.QueryRow(ctx, getActiveSessionForChild, childID)
	var i AppSession
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.SocialMediaID,
		&i.StartTime,
		&i.EndTime,
		&i.ExpectedEndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPingTime,
	)
	return i, err
}

const getAppSessionByID = `-- name: GetAppSessionByID :one
SELECT id, child_id, social_media_id, start_time, end_time, expected_end_time, status, created_at, updated_at, last_ping_time FROM app_sessions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAppSessionByID(ctx context.Context, id uuid.UUID) (AppSession, error) {
	row := q.db.QueryRow(ctx, getAppSessionByID, id)
	var i AppSession
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.SocialMediaID,
		&i.StartTime,
		&i.EndTime,
		&i.ExpectedEndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPingTime,
	)
	return i, err
}

const getDailyUsageForWeek = `-- name: GetDailyUsageForWeek :many
SELECT
    DATE_TRUNC('day', start_time)::date as usage_date,
    CAST(SUM(
        EXTRACT(EPOCH FROM (LEAST(COALESCE(end_time, last_ping_time, start_time), start_time + INTERVAL '1 day') - start_time))
    ) / 60.0 AS float) AS total_minutes
FROM
    app_sessions
WHERE
    child_id = $1
    AND social_media_id = $2
    AND start_time >= $3
    AND start_time < $4
GROUP BY
    usage_date
ORDER BY
    usage_date
`

type GetDailyUsageForWeekParams struct {
	ChildID       string    `json:"child_id"`
	SocialMediaID int64     `json:"social_media_id"`
	StartTime     time.Time `json:"start_time"`
	StartTime_2   time.Time `json:"start_time_2"`
}

type GetDailyUsageForWeekRow struct {
	UsageDate    pgtype.Date `json:"usage_date"`
	TotalMinutes float64     `json:"total_minutes"`
}

func (q *Queries) GetDailyUsageForWeek(ctx context.Context, arg GetDailyUsageForWeekParams) ([]GetDailyUsageForWeekRow, error) {
	rows, err := q.db.Query(ctx, getDailyUsageForWeek,
		arg.ChildID,
		arg.SocialMediaID,
		arg.StartTime,
		arg.StartTime_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyUsageForWeekRow{}
	for rows.Next() {
		var i GetDailyUsageForWeekRow
		if err := rows.Scan(&i.UsageDate, &i.TotalMinutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageSummaryForDate = `-- name: GetUsageSummaryForDate :many
SELECT
    sm.id as social_media_id,
    sm.name as social_media_name,
    sm.icon_url as social_media_logo,
    CAST(SUM(
        EXTRACT(EPOCH FROM (LEAST(COALESCE(s.end_time, NOW()), $3) - s.start_time))
    ) / 60.0 AS float) AS total_minutes
FROM
    app_sessions s
JOIN
    social_medias sm ON s.social_media_id = sm.id
WHERE
    s.child_id = $1
    AND s.start_time >= $2
    AND s.start_time < $3
GROUP BY
    sm.id, sm.name, sm.icon_url
ORDER BY
    total_minutes DESC
`

type GetUsageSummaryForDateParams struct {
	ChildID   string             `json:"child_id"`
	StartTime time.Time          `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type GetUsageSummaryForDateRow struct {
	SocialMediaID   int64       `json:"social_media_id"`
	SocialMediaName string      `json:"social_media_name"`
	SocialMediaLogo pgtype.Text `json:"social_media_logo"`
	TotalMinutes    float64     `json:"total_minutes"`
}

func (q *Queries) GetUsageSummaryForDate(ctx context.Context, arg GetUsageSummaryForDateParams) ([]GetUsageSummaryForDateRow, error) {
	rows, err := q.db.Query(ctx, getUsageSummaryForDate, arg.ChildID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsageSummaryForDateRow{}
	for rows.Next() {
		var i GetUsageSummaryForDateRow
		if err := rows.Scan(
			&i.SocialMediaID,
			&i.SocialMediaName,
			&i.SocialMediaLogo,
			&i.TotalMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const timeoutStaleSessions = `-- name: TimeoutStaleSessions :many
UPDATE app_sessions
SET
    end_time = expected_end_time,
    status = 'timed_out',
    updated_at = NOW()
WHERE
    status = 'active' AND expected_end_time <= NOW()
RETURNING id, child_id, social_media_id, start_time, end_time, expected_end_time, status, created_at, updated_at, last_ping_time
`

func (q *Queries) TimeoutStaleSessions(ctx context.Context) ([]AppSession, error) {
	rows, err := q.db.Query(ctx, timeoutStaleSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSession{}
	for rows.Next() {
		var i AppSession
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.SocialMediaID,
			&i.StartTime,
			&i.EndTime,
			&i.ExpectedEndTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastPingTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionPing = `-- name: UpdateSessionPing :one
UPDATE app_sessions
SET last_ping_time = NOW()
WHERE id = $1
RETURNING id, child_id, social_media_id, start_time, end_time, expected_end_time, status, created_at, updated_at, last_ping_time
`

func (q *Queries) UpdateSessionPing(ctx context.Context, id uuid.UUID) (AppSession, error) {
	row := q.db.QueryRow(ctx, updateSessionPing, id)
	var i AppSession
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.SocialMediaID,
		&i.StartTime,
		&i.EndTime,
		&i.ExpectedEndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPingTime,
	)
	return i, err
}

const getTodayExpiredSessionByChildAndApp = `-- name: GetTodayExpiredSessionByChildAndApp :one
SELECT id, child_id, social_media_id, start_time, end_time, expected_end_time, status, created_at, updated_at, last_ping_time FROM app_sessions
WHERE child_id = $1
  AND social_media_id = $2
  AND status IN ('expired', 'ended')
  AND start_time >= DATE_TRUNC('day', NOW() AT TIME ZONE 'UTC')
  AND start_time <  DATE_TRUNC('day', NOW() AT TIME ZONE 'UTC') + INTERVAL '1 day'
ORDER BY start_time DESC
LIMIT 1
`

type GetTodayExpiredSessionByChildAndAppParams struct {
	ChildID       string `json:"child_id"`
	SocialMediaID int64  `json:"social_media_id"`
}

func (q *Queries) GetTodayExpiredSessionByChildAndApp(ctx context.Context, arg GetTodayExpiredSessionByChildAndAppParams) (AppSession, error) {
	row := q.db.QueryRow(ctx, getTodayExpiredSessionByChildAndApp, arg.ChildID, arg.SocialMediaID)
	var i AppSession
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.SocialMediaID,
		&i.StartTime,
		&i.EndTime,
		&i.ExpectedEndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPingTime,
	)
	return i, err
}

const getActiveSessionByChildAndApp = `-- name: GetActiveSessionByChildAndApp :one
SELECT id, child_id, social_media_id, start_time, end_time, expected_end_time, status, created_at, updated_at, last_ping_time FROM app_sessions
WHERE child_id = $1 AND social_media_id = $2 AND status = 'active'
ORDER BY start_time DESC
LIMIT 1
`

type GetActiveSessionByChildAndAppParams struct {
	ChildID       string `json:"child_id"`
	SocialMediaID int64  `json:"social_media_id"`
}

func (q *Queries) GetActiveSessionByChildAndApp(ctx context.Context, arg GetActiveSessionByChildAndAppParams) (AppSession, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByChildAndApp, arg.ChildID, arg.SocialMediaID)
	var i AppSession
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.SocialMediaID,
		&i.StartTime,
		&i.EndTime,
		&i.ExpectedEndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPingTime,
	)
	return i, err
}

const getExpiredActiveSessions = `-- name: GetExpiredActiveSessions :many
SELECT id, child_id, social_media_id, start_time, end_time, expected_end_time, status, created_at, updated_at, last_ping_time FROM app_sessions
WHERE status = 'active' AND expected_end_time <= NOW()
`

func (q *Queries) GetExpiredActiveSessions(ctx context.Context) ([]AppSession, error) {
	rows, err := q.db.Query(ctx, getExpiredActiveSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSession{}
	for rows.Next() {
		var i AppSession
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.SocialMediaID,
			&i.StartTime,
			&i.EndTime,
			&i.ExpectedEndTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastPingTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionExpired = `-- name: MarkSessionExpired :one
UPDATE app_sessions
SET status = 'expired', end_time = expected_end_time, updated_at = NOW()
WHERE id = $1
RETURNING id, child_id, social_media_id, start_time, end_time, expected_end_time, status, created_at, updated_at, last_ping_time
`

func (q *Queries) MarkSessionExpired(ctx context.Context, id uuid.UUID) (AppSession, error) {
	row := q.db.QueryRow(ctx, markSessionExpired, id)
	var i AppSession
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.SocialMediaID,
		&i.StartTime,
		&i.EndTime,
		&i.ExpectedEndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPingTime,
	)
	return i, err
}

const markSessionEnded = `-- name: MarkSessionEnded :one
UPDATE app_sessions
SET status = 'ended', end_time = NOW(), updated_at = NOW()
WHERE child_id = $1 AND social_media_id = $2 AND status = 'active'
RETURNING id, child_id, social_media_id, start_time, end_time, expected_end_time, status, created_at, updated_at, last_ping_time
`

type MarkSessionEndedParams struct {
	ChildID       string `json:"child_id"`
	SocialMediaID int64  `json:"social_media_id"`
}

func (q *Queries) MarkSessionEnded(ctx context.Context, arg MarkSessionEndedParams) (AppSession, error) {
	row := q.db.QueryRow(ctx, markSessionEnded, arg.ChildID, arg.SocialMediaID)
	var i AppSession
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.SocialMediaID,
		&i.StartTime,
		&i.EndTime,
		&i.ExpectedEndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPingTime,
	)
	return i, err
}
