// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: booster.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignBoosterToChild = `-- name: AssignBoosterToChild :one
INSERT INTO child_weekly_modules (
  child_id,
  external_module_id,
  week_start_date,
  booster_id
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, child_id, external_module_id, week_start_date, shown_at, completed_at, latest_score, booster_id
`

type AssignBoosterToChildParams struct {
	ChildID          string      `json:"child_id"`
	ExternalModuleID string      `json:"external_module_id"`
	WeekStartDate    pgtype.Date `json:"week_start_date"`
	BoosterID        string      `json:"booster_id"`
}

func (q *Queries) AssignBoosterToChild(ctx context.Context, arg AssignBoosterToChildParams) (ChildWeeklyModule, error) {
	row := q.db.QueryRow(ctx, assignBoosterToChild,
		arg.ChildID,
		arg.ExternalModuleID,
		arg.WeekStartDate,
		arg.BoosterID,
	)
	var i ChildWeeklyModule
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.ExternalModuleID,
		&i.WeekStartDate,
		&i.ShownAt,
		&i.CompletedAt,
		&i.LatestScore,
		&i.BoosterID,
	)
	return i, err
}

const completeBooster = `-- name: CompleteBooster :one
UPDATE child_weekly_modules
SET completed_at = now()
WHERE booster_id = $1
RETURNING id, child_id, external_module_id, week_start_date, shown_at, completed_at, latest_score, booster_id
`

func (q *Queries) CompleteBooster(ctx context.Context, boosterID string) (ChildWeeklyModule, error) {
	row := q.db.QueryRow(ctx, completeBooster, boosterID)
	var i ChildWeeklyModule
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.ExternalModuleID,
		&i.WeekStartDate,
		&i.ShownAt,
		&i.CompletedAt,
		&i.LatestScore,
		&i.BoosterID,
	)
	return i, err
}

const getAssignedBoosterModuleIDsForChild = `-- name: GetAssignedBoosterModuleIDsForChild :many
SELECT external_module_id FROM child_weekly_modules
WHERE child_id = $1
`

func (q *Queries) GetAssignedBoosterModuleIDsForChild(ctx context.Context, childID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getAssignedBoosterModuleIDsForChild, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var external_module_id string
		if err := rows.Scan(&external_module_id); err != nil {
			return nil, err
		}
		items = append(items, external_module_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBoosterByID = `-- name: GetBoosterByID :one
SELECT id, child_id, external_module_id, week_start_date, shown_at, completed_at, latest_score, booster_id FROM child_weekly_modules
WHERE booster_id = $1
`

func (q *Queries) GetBoosterByID(ctx context.Context, boosterID string) (ChildWeeklyModule, error) {
	row := q.db.QueryRow(ctx, getBoosterByID, boosterID)
	var i ChildWeeklyModule
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.ExternalModuleID,
		&i.WeekStartDate,
		&i.ShownAt,
		&i.CompletedAt,
		&i.LatestScore,
		&i.BoosterID,
	)
	return i, err
}

const getBoostersForChildByParent = `-- name: GetBoostersForChildByParent :many
SELECT
    cwm.id, cwm.child_id, cwm.external_module_id, cwm.week_start_date, cwm.shown_at, cwm.completed_at, cwm.latest_score, cwm.booster_id,
    rv.video_url AS reflection_video_url,
    rv.created_at AS reflection_submitted_at
FROM
    child_weekly_modules cwm
LEFT JOIN
    reflection_videos rv ON cwm.booster_id = rv.booster_id
WHERE
    cwm.child_id = $1
    AND cwm.week_start_date <= date_trunc('week', now() at time zone 'utc')
ORDER BY
    cwm.week_start_date DESC
`

type GetBoostersForChildByParentRow struct {
	ID                    int64              `json:"id"`
	ChildID               string             `json:"child_id"`
	ExternalModuleID      string             `json:"external_module_id"`
	WeekStartDate         pgtype.Date        `json:"week_start_date"`
	ShownAt               pgtype.Timestamptz `json:"shown_at"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	LatestScore           pgtype.Numeric     `json:"latest_score"`
	BoosterID             string             `json:"booster_id"`
	ReflectionVideoUrl    pgtype.Text        `json:"reflection_video_url"`
	ReflectionSubmittedAt pgtype.Timestamptz `json:"reflection_submitted_at"`
}

func (q *Queries) GetBoostersForChildByParent(ctx context.Context, childID string) ([]GetBoostersForChildByParentRow, error) {
	rows, err := q.db.Query(ctx, getBoostersForChildByParent, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBoostersForChildByParentRow{}
	for rows.Next() {
		var i GetBoostersForChildByParentRow
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.ExternalModuleID,
			&i.WeekStartDate,
			&i.ShownAt,
			&i.CompletedAt,
			&i.LatestScore,
			&i.BoosterID,
			&i.ReflectionVideoUrl,
			&i.ReflectionSubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBoostersForChildInMonth = `-- name: GetBoostersForChildInMonth :many
SELECT
    booster_id,
    completed_at
FROM
    child_weekly_modules
WHERE
    child_id = $1
    AND completed_at >= date_trunc('month', CURRENT_DATE)
    AND completed_at < date_trunc('month', CURRENT_DATE) + interval '1 month'
`

type GetBoostersForChildInMonthRow struct {
	BoosterID   string             `json:"booster_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) GetBoostersForChildInMonth(ctx context.Context, childID string) ([]GetBoostersForChildInMonthRow, error) {
	rows, err := q.db.Query(ctx, getBoostersForChildInMonth, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBoostersForChildInMonthRow{}
	for rows.Next() {
		var i GetBoostersForChildInMonthRow
		if err := rows.Scan(&i.BoosterID, &i.CompletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChildBoosterByWeek = `-- name: GetChildBoosterByWeek :one
SELECT id, child_id, external_module_id, week_start_date, shown_at, completed_at, latest_score, booster_id FROM child_weekly_modules
WHERE child_id = $1 AND week_start_date = $2
`

type GetChildBoosterByWeekParams struct {
	ChildID       string      `json:"child_id"`
	WeekStartDate pgtype.Date `json:"week_start_date"`
}

func (q *Queries) GetChildBoosterByWeek(ctx context.Context, arg GetChildBoosterByWeekParams) (ChildWeeklyModule, error) {
	row := q.db.QueryRow(ctx, getChildBoosterByWeek, arg.ChildID, arg.WeekStartDate)
	var i ChildWeeklyModule
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.ExternalModuleID,
		&i.WeekStartDate,
		&i.ShownAt,
		&i.CompletedAt,
		&i.LatestScore,
		&i.BoosterID,
	)
	return i, err
}

const getCurrentBoosterForChild = `-- name: GetCurrentBoosterForChild :one
SELECT id, child_id, external_module_id, week_start_date, shown_at, completed_at, latest_score, booster_id FROM child_weekly_modules
WHERE child_id = $1 AND week_start_date = date_trunc('week', now() at time zone 'utc')
`

func (q *Queries) GetCurrentBoosterForChild(ctx context.Context, childID string) (ChildWeeklyModule, error) {
	row := q.db.QueryRow(ctx, getCurrentBoosterForChild, childID)
	var i ChildWeeklyModule
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.ExternalModuleID,
		&i.WeekStartDate,
		&i.ShownAt,
		&i.CompletedAt,
		&i.LatestScore,
		&i.BoosterID,
	)
	return i, err
}

const getNextBoosterForChild = `-- name: GetNextBoosterForChild :one
SELECT id, child_id, external_module_id, week_start_date, shown_at, completed_at, latest_score, booster_id FROM child_weekly_modules
WHERE child_id = $1 AND week_start_date = date_trunc('week', now() at time zone 'utc' + interval '1 week')
`

func (q *Queries) GetNextBoosterForChild(ctx context.Context, childID string) (ChildWeeklyModule, error) {
	row := q.db.QueryRow(ctx, getNextBoosterForChild, childID)
	var i ChildWeeklyModule
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.ExternalModuleID,
		&i.WeekStartDate,
		&i.ShownAt,
		&i.CompletedAt,
		&i.LatestScore,
		&i.BoosterID,
	)
	return i, err
}

const getReflectionVideoForBooster = `-- name: GetReflectionVideoForBooster :one
SELECT id, child_id, booster_id, video_url, strapi_asset_id, created_at FROM reflection_videos
WHERE booster_id = $1
LIMIT 1
`

func (q *Queries) GetReflectionVideoForBooster(ctx context.Context, boosterID string) (ReflectionVideo, error) {
	row := q.db.QueryRow(ctx, getReflectionVideoForBooster, boosterID)
	var i ReflectionVideo
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.BoosterID,
		&i.VideoUrl,
		&i.StrapiAssetID,
		&i.CreatedAt,
	)
	return i, err
}

const getReflectionVideosForChild = `-- name: GetReflectionVideosForChild :many
SELECT
    rv.id,
    rv.child_id,
    rv.booster_id,
    rv.video_url,
    rv.strapi_asset_id,
    rv.created_at,
    cwm.external_module_id
FROM
    reflection_videos rv
JOIN
    child_weekly_modules cwm ON rv.booster_id = cwm.booster_id
WHERE
    rv.child_id = $1
ORDER BY
    rv.created_at DESC
`

type GetReflectionVideosForChildRow struct {
	ID               int64       `json:"id"`
	ChildID          string      `json:"child_id"`
	BoosterID        string      `json:"booster_id"`
	VideoUrl         string      `json:"video_url"`
	StrapiAssetID    pgtype.Text `json:"strapi_asset_id"`
	CreatedAt        time.Time   `json:"created_at"`
	ExternalModuleID string      `json:"external_module_id"`
}

func (q *Queries) GetReflectionVideosForChild(ctx context.Context, childID string) ([]GetReflectionVideosForChildRow, error) {
	rows, err := q.db.Query(ctx, getReflectionVideosForChild, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReflectionVideosForChildRow{}
	for rows.Next() {
		var i GetReflectionVideosForChildRow
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.BoosterID,
			&i.VideoUrl,
			&i.StrapiAssetID,
			&i.CreatedAt,
			&i.ExternalModuleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
