// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: child_activity_log.sql

package db

import (
	"context"
)

const checkChildActivityExists = `-- name: CheckChildActivityExists :one
SELECT EXISTS(
  SELECT 1 FROM child_activity_log
  WHERE child_id = $1 AND activity_type = $2 AND activity_ref_id = $3
)
`

type CheckChildActivityExistsParams struct {
	ChildID       string            `json:"child_id"`
	ActivityType  ChildActivityType `json:"activity_type"`
	ActivityRefID string            `json:"activity_ref_id"`
}

func (q *Queries) CheckChildActivityExists(ctx context.Context, arg CheckChildActivityExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkChildActivityExists, arg.ChildID, arg.ActivityType, arg.ActivityRefID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const logChildActivity = `-- name: LogChildActivity :one
INSERT INTO child_activity_log (
  child_id,
  activity_type,
  activity_ref_id
) VALUES (
  $1, $2, $3
)
ON CONFLICT (child_id, activity_type, activity_ref_id) DO NOTHING
RETURNING id, child_id, activity_type, activity_ref_id, created_at
`

type LogChildActivityParams struct {
	ChildID       string            `json:"child_id"`
	ActivityType  ChildActivityType `json:"activity_type"`
	ActivityRefID string            `json:"activity_ref_id"`
}

func (q *Queries) LogChildActivity(ctx context.Context, arg LogChildActivityParams) (ChildActivityLog, error) {
	row := q.db.QueryRow(ctx, logChildActivity, arg.ChildID, arg.ActivityType, arg.ActivityRefID)
	var i ChildActivityLog
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.ActivityType,
		&i.ActivityRefID,
		&i.CreatedAt,
	)
	return i, err
}
