// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: children.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChild = `-- name: CreateChild :one
INSERT INTO children (
    id,
    family_id,
    first_name,
    surname,
    age,
    gender,
    profile_image_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, family_id, first_name, surname, age, gender, profile_image_url, created_at, updated_at, push_notifications_enabled, deleted_at
`

type CreateChildParams struct {
	ID              string      `json:"id"`
	FamilyID        string      `json:"family_id"`
	FirstName       string      `json:"first_name"`
	Surname         string      `json:"surname"`
	Age             pgtype.Int4 `json:"age"`
	Gender          pgtype.Text `json:"gender"`
	ProfileImageUrl pgtype.Text `json:"profile_image_url"`
}

func (q *Queries) CreateChild(ctx context.Context, arg CreateChildParams) (Child, error) {
	row := q.db.QueryRow(ctx, createChild,
		arg.ID,
		arg.FamilyID,
		arg.FirstName,
		arg.Surname,
		arg.Age,
		arg.Gender,
		arg.ProfileImageUrl,
	)
	var i Child
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.FirstName,
		&i.Surname,
		&i.Age,
		&i.Gender,
		&i.ProfileImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushNotificationsEnabled,
		&i.DeletedAt,
	)
	return i, err
}

const deleteChild = `-- name: DeleteChild :exec
DELETE FROM children
WHERE id = $1
`

func (q *Queries) DeleteChild(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteChild, id)
	return err
}

const getChild = `-- name: GetChild :one
SELECT id, family_id, first_name, surname, age, gender, profile_image_url, created_at, updated_at, push_notifications_enabled, deleted_at FROM children
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetChild(ctx context.Context, id string) (Child, error) {
	row := q.db.QueryRow(ctx, getChild, id)
	var i Child
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.FirstName,
		&i.Surname,
		&i.Age,
		&i.Gender,
		&i.ProfileImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushNotificationsEnabled,
		&i.DeletedAt,
	)
	return i, err
}

const getChildrenByFamilyID = `-- name: GetChildrenByFamilyID :many
SELECT id, family_id, first_name, surname, age, gender, profile_image_url, created_at, updated_at, push_notifications_enabled, deleted_at FROM children
WHERE family_id = $1 AND deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) GetChildrenByFamilyID(ctx context.Context, familyID string) ([]Child, error) {
	rows, err := q.db.Query(ctx, getChildrenByFamilyID, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Child{}
	for rows.Next() {
		var i Child
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.FirstName,
			&i.Surname,
			&i.Age,
			&i.Gender,
			&i.ProfileImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PushNotificationsEnabled,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteChild = `-- name: SoftDeleteChild :exec
UPDATE children
SET deleted_at = NOW()
WHERE id = $1 AND family_id = $2 AND deleted_at IS NULL
`

type SoftDeleteChildParams struct {
	ID       string `json:"id"`
	FamilyID string `json:"family_id"`
}

func (q *Queries) SoftDeleteChild(ctx context.Context, arg SoftDeleteChildParams) error {
	_, err := q.db.Exec(ctx, softDeleteChild, arg.ID, arg.FamilyID)
	return err
}
