// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: child_weekly_modules.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChildWeeklyModule = `-- name: GetChildWeeklyModule :one
SELECT id, child_id, external_module_id, week_start_date, shown_at, completed_at, latest_score, booster_id FROM child_weekly_modules
WHERE child_id = $1 AND external_module_id = $2
`

type GetChildWeeklyModuleParams struct {
	ChildID          string `json:"child_id"`
	ExternalModuleID string `json:"external_module_id"`
}

func (q *Queries) GetChildWeeklyModule(ctx context.Context, arg GetChildWeeklyModuleParams) (ChildWeeklyModule, error) {
	row := q.db.QueryRow(ctx, getChildWeeklyModule, arg.ChildID, arg.ExternalModuleID)
	var i ChildWeeklyModule
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.ExternalModuleID,
		&i.WeekStartDate,
		&i.ShownAt,
		&i.CompletedAt,
		&i.LatestScore,
		&i.BoosterID,
	)
	return i, err
}

const updateChildWeeklyModuleProgress = `-- name: UpdateChildWeeklyModuleProgress :one
UPDATE child_weekly_modules
SET 
  completed_at = $1,
  latest_score = $2
WHERE child_id = $3 AND external_module_id = $4
RETURNING id, child_id, external_module_id, week_start_date, shown_at, completed_at, latest_score, booster_id
`

type UpdateChildWeeklyModuleProgressParams struct {
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	LatestScore      pgtype.Numeric     `json:"latest_score"`
	ChildID          string             `json:"child_id"`
	ExternalModuleID string             `json:"external_module_id"`
}

func (q *Queries) UpdateChildWeeklyModuleProgress(ctx context.Context, arg UpdateChildWeeklyModuleProgressParams) (ChildWeeklyModule, error) {
	row := q.db.QueryRow(ctx, updateChildWeeklyModuleProgress,
		arg.CompletedAt,
		arg.LatestScore,
		arg.ChildID,
		arg.ExternalModuleID,
	)
	var i ChildWeeklyModule
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.ExternalModuleID,
		&i.WeekStartDate,
		&i.ShownAt,
		&i.CompletedAt,
		&i.LatestScore,
		&i.BoosterID,
	)
	return i, err
}
