// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: child_weekly_module.sql

package db

import (
	"context"
)

const getChildWeeklyModuleProgress = `-- name: GetChildWeeklyModuleProgress :one
SELECT id, child_id, external_module_id, week_start_date, shown_at, completed_at, latest_score
FROM child_weekly_modules
WHERE child_id = $1 AND external_module_id = $2
`

type GetChildWeeklyModuleProgressParams struct {
	ChildID          string `json:"child_id"`
	ExternalModuleID string `json:"external_module_id"`
}

func (q *Queries) GetChildWeeklyModuleProgress(ctx context.Context, arg GetChildWeeklyModuleProgressParams) (ChildWeeklyModule, error) {
	row := q.db.QueryRow(ctx, getChildWeeklyModuleProgress, arg.ChildID, arg.ExternalModuleID)
	var i ChildWeeklyModule
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.ExternalModuleID,
		&i.WeekStartDate,
		&i.ShownAt,
		&i.CompletedAt,
		&i.LatestScore,
	)
	return i, err
}
