// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: child_reflection_context.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChildReflectionContext = `-- name: GetChildReflectionContext :one
SELECT child_id, total_modules_completed, total_quizzes_taken, average_quiz_score, digital_permit_status, digital_permit_score, last_activity_date, recent_activities, completed_module_ids, total_sm_sessions, avg_daily_sm_minutes, most_used_apps, frequent_content_categories, last_session_end, last_reflection_acknowledged, reflection_streak, total_reflections_responded, total_reflections_delivered, updated_at FROM child_reflection_context WHERE child_id = $1 LIMIT 1
`

func (q *Queries) GetChildReflectionContext(ctx context.Context, childID string) (ChildReflectionContext, error) {
	row := q.db.QueryRow(ctx, getChildReflectionContext, childID)
	var i ChildReflectionContext
	err := row.Scan(
		&i.ChildID,
		&i.TotalModulesCompleted,
		&i.TotalQuizzesTaken,
		&i.AverageQuizScore,
		&i.DigitalPermitStatus,
		&i.DigitalPermitScore,
		&i.LastActivityDate,
		&i.RecentActivities,
		&i.CompletedModuleIds,
		&i.TotalSmSessions,
		&i.AvgDailySmMinutes,
		&i.MostUsedApps,
		&i.FrequentContentCategories,
		&i.LastSessionEnd,
		&i.LastReflectionAcknowledged,
		&i.ReflectionStreak,
		&i.TotalReflectionsResponded,
		&i.TotalReflectionsDelivered,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementReflectionsDelivered = `-- name: IncrementReflectionsDelivered :exec
UPDATE child_reflection_context
SET total_reflections_delivered = total_reflections_delivered + 1, updated_at = now()
WHERE child_id = $1
`

func (q *Queries) IncrementReflectionsDelivered(ctx context.Context, childID string) error {
	_, err := q.db.Exec(ctx, incrementReflectionsDelivered, childID)
	return err
}

const incrementReflectionsResponded = `-- name: IncrementReflectionsResponded :exec
UPDATE child_reflection_context
SET total_reflections_responded = total_reflections_responded + 1, updated_at = now()
WHERE child_id = $1
`

func (q *Queries) IncrementReflectionsResponded(ctx context.Context, childID string) error {
	_, err := q.db.Exec(ctx, incrementReflectionsResponded, childID)
	return err
}

const updateReflectionAcknowledgment = `-- name: UpdateReflectionAcknowledgment :exec
UPDATE child_reflection_context
SET
  last_reflection_acknowledged = $2,
  updated_at                   = now()
WHERE child_id = $1
`

type UpdateReflectionAcknowledgmentParams struct {
	ChildID                    string `json:"child_id"`
	LastReflectionAcknowledged bool   `json:"last_reflection_acknowledged"`
}

func (q *Queries) UpdateReflectionAcknowledgment(ctx context.Context, arg UpdateReflectionAcknowledgmentParams) error {
	_, err := q.db.Exec(ctx, updateReflectionAcknowledgment, arg.ChildID, arg.LastReflectionAcknowledged)
	return err
}

const upsertChildReflectionContext = `-- name: UpsertChildReflectionContext :one
INSERT INTO child_reflection_context (
  child_id,
  total_modules_completed,
  total_quizzes_taken,
  average_quiz_score,
  digital_permit_status,
  digital_permit_score,
  last_activity_date,
  recent_activities,
  completed_module_ids,
  total_sm_sessions,
  avg_daily_sm_minutes,
  most_used_apps,
  frequent_content_categories,
  last_session_end,
  last_reflection_acknowledged,
  reflection_streak,
  total_reflections_responded,
  total_reflections_delivered,
  updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, now()
)
ON CONFLICT (child_id) DO UPDATE SET
  total_modules_completed      = EXCLUDED.total_modules_completed,
  total_quizzes_taken          = EXCLUDED.total_quizzes_taken,
  average_quiz_score           = EXCLUDED.average_quiz_score,
  digital_permit_status        = EXCLUDED.digital_permit_status,
  digital_permit_score         = EXCLUDED.digital_permit_score,
  last_activity_date           = EXCLUDED.last_activity_date,
  recent_activities            = EXCLUDED.recent_activities,
  completed_module_ids         = EXCLUDED.completed_module_ids,
  total_sm_sessions            = EXCLUDED.total_sm_sessions,
  avg_daily_sm_minutes         = EXCLUDED.avg_daily_sm_minutes,
  most_used_apps               = EXCLUDED.most_used_apps,
  frequent_content_categories  = EXCLUDED.frequent_content_categories,
  last_session_end             = EXCLUDED.last_session_end,
  last_reflection_acknowledged = EXCLUDED.last_reflection_acknowledged,
  reflection_streak            = EXCLUDED.reflection_streak,
  total_reflections_responded  = EXCLUDED.total_reflections_responded,
  total_reflections_delivered  = EXCLUDED.total_reflections_delivered,
  updated_at                   = now()
RETURNING child_id, total_modules_completed, total_quizzes_taken, average_quiz_score, digital_permit_status, digital_permit_score, last_activity_date, recent_activities, completed_module_ids, total_sm_sessions, avg_daily_sm_minutes, most_used_apps, frequent_content_categories, last_session_end, last_reflection_acknowledged, reflection_streak, total_reflections_responded, total_reflections_delivered, updated_at
`

type UpsertChildReflectionContextParams struct {
	ChildID                    string             `json:"child_id"`
	TotalModulesCompleted      int32              `json:"total_modules_completed"`
	TotalQuizzesTaken          int32              `json:"total_quizzes_taken"`
	AverageQuizScore           pgtype.Numeric     `json:"average_quiz_score"`
	DigitalPermitStatus        pgtype.Text        `json:"digital_permit_status"`
	DigitalPermitScore         pgtype.Numeric     `json:"digital_permit_score"`
	LastActivityDate           pgtype.Timestamptz `json:"last_activity_date"`
	RecentActivities           []byte             `json:"recent_activities"`
	CompletedModuleIds         []string           `json:"completed_module_ids"`
	TotalSmSessions            int32              `json:"total_sm_sessions"`
	AvgDailySmMinutes          pgtype.Numeric     `json:"avg_daily_sm_minutes"`
	MostUsedApps               []byte             `json:"most_used_apps"`
	FrequentContentCategories  []string           `json:"frequent_content_categories"`
	LastSessionEnd             pgtype.Timestamptz `json:"last_session_end"`
	LastReflectionAcknowledged bool               `json:"last_reflection_acknowledged"`
	ReflectionStreak           int32              `json:"reflection_streak"`
	TotalReflectionsResponded  int32              `json:"total_reflections_responded"`
	TotalReflectionsDelivered  int32              `json:"total_reflections_delivered"`
}

func (q *Queries) UpsertChildReflectionContext(ctx context.Context, arg UpsertChildReflectionContextParams) (ChildReflectionContext, error) {
	row := q.db.QueryRow(ctx, upsertChildReflectionContext,
		arg.ChildID,
		arg.TotalModulesCompleted,
		arg.TotalQuizzesTaken,
		arg.AverageQuizScore,
		arg.DigitalPermitStatus,
		arg.DigitalPermitScore,
		arg.LastActivityDate,
		arg.RecentActivities,
		arg.CompletedModuleIds,
		arg.TotalSmSessions,
		arg.AvgDailySmMinutes,
		arg.MostUsedApps,
		arg.FrequentContentCategories,
		arg.LastSessionEnd,
		arg.LastReflectionAcknowledged,
		arg.ReflectionStreak,
		arg.TotalReflectionsResponded,
		arg.TotalReflectionsDelivered,
	)
	var i ChildReflectionContext
	err := row.Scan(
		&i.ChildID,
		&i.TotalModulesCompleted,
		&i.TotalQuizzesTaken,
		&i.AverageQuizScore,
		&i.DigitalPermitStatus,
		&i.DigitalPermitScore,
		&i.LastActivityDate,
		&i.RecentActivities,
		&i.CompletedModuleIds,
		&i.TotalSmSessions,
		&i.AvgDailySmMinutes,
		&i.MostUsedApps,
		&i.FrequentContentCategories,
		&i.LastSessionEnd,
		&i.LastReflectionAcknowledged,
		&i.ReflectionStreak,
		&i.TotalReflectionsResponded,
		&i.TotalReflectionsDelivered,
		&i.UpdatedAt,
	)
	return i, err
}
