// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: child_quiz_answers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChildQuizAnswer = `-- name: CreateChildQuizAnswer :one
INSERT INTO child_quiz_answers (
  child_id,
  course_id,
  module_id,
  external_quiz_id,
  attempt_number,
  external_question_id,
  selected_answer_option_ids,
  is_correct,
  score
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, child_id, course_id, module_id, external_quiz_id, attempt_number, external_question_id, selected_answer_option_ids, is_correct, score, created_at
`

type CreateChildQuizAnswerParams struct {
	ChildID                 string         `json:"child_id"`
	CourseID                string         `json:"course_id"`
	ModuleID                string         `json:"module_id"`
	ExternalQuizID          string         `json:"external_quiz_id"`
	AttemptNumber           int32          `json:"attempt_number"`
	ExternalQuestionID      string         `json:"external_question_id"`
	SelectedAnswerOptionIds []string       `json:"selected_answer_option_ids"`
	IsCorrect               bool           `json:"is_correct"`
	Score                   pgtype.Numeric `json:"score"`
}

func (q *Queries) CreateChildQuizAnswer(ctx context.Context, arg CreateChildQuizAnswerParams) (ChildQuizAnswer, error) {
	row := q.db.QueryRow(ctx, createChildQuizAnswer,
		arg.ChildID,
		arg.CourseID,
		arg.ModuleID,
		arg.ExternalQuizID,
		arg.AttemptNumber,
		arg.ExternalQuestionID,
		arg.SelectedAnswerOptionIds,
		arg.IsCorrect,
		arg.Score,
	)
	var i ChildQuizAnswer
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.CourseID,
		&i.ModuleID,
		&i.ExternalQuizID,
		&i.AttemptNumber,
		&i.ExternalQuestionID,
		&i.SelectedAnswerOptionIds,
		&i.IsCorrect,
		&i.Score,
		&i.CreatedAt,
	)
	return i, err
}

const getChildQuizAnswersByAttempt = `-- name: GetChildQuizAnswersByAttempt :many
SELECT id, child_id, course_id, module_id, external_quiz_id, attempt_number, external_question_id, selected_answer_option_ids, is_correct, score, created_at FROM child_quiz_answers
WHERE child_id = $1 AND course_id = $2 AND module_id = $3 AND external_quiz_id = $4 AND attempt_number = $5
`

type GetChildQuizAnswersByAttemptParams struct {
	ChildID        string `json:"child_id"`
	CourseID       string `json:"course_id"`
	ModuleID       string `json:"module_id"`
	ExternalQuizID string `json:"external_quiz_id"`
	AttemptNumber  int32  `json:"attempt_number"`
}

func (q *Queries) GetChildQuizAnswersByAttempt(ctx context.Context, arg GetChildQuizAnswersByAttemptParams) ([]ChildQuizAnswer, error) {
	rows, err := q.db.Query(ctx, getChildQuizAnswersByAttempt,
		arg.ChildID,
		arg.CourseID,
		arg.ModuleID,
		arg.ExternalQuizID,
		arg.AttemptNumber,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChildQuizAnswer{}
	for rows.Next() {
		var i ChildQuizAnswer
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.CourseID,
			&i.ModuleID,
			&i.ExternalQuizID,
			&i.AttemptNumber,
			&i.ExternalQuestionID,
			&i.SelectedAnswerOptionIds,
			&i.IsCorrect,
			&i.Score,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChildQuizAnswersByQuiz = `-- name: GetChildQuizAnswersByQuiz :many
SELECT id, child_id, course_id, module_id, external_quiz_id, attempt_number, external_question_id, selected_answer_option_ids, is_correct, score, created_at FROM child_quiz_answers
WHERE child_id = $1 AND course_id = $2 AND module_id = $3 AND external_quiz_id = $4
`

type GetChildQuizAnswersByQuizParams struct {
	ChildID        string `json:"child_id"`
	CourseID       string `json:"course_id"`
	ModuleID       string `json:"module_id"`
	ExternalQuizID string `json:"external_quiz_id"`
}

func (q *Queries) GetChildQuizAnswersByQuiz(ctx context.Context, arg GetChildQuizAnswersByQuizParams) ([]ChildQuizAnswer, error) {
	rows, err := q.db.Query(ctx, getChildQuizAnswersByQuiz,
		arg.ChildID,
		arg.CourseID,
		arg.ModuleID,
		arg.ExternalQuizID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChildQuizAnswer{}
	for rows.Next() {
		var i ChildQuizAnswer
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.CourseID,
			&i.ModuleID,
			&i.ExternalQuizID,
			&i.AttemptNumber,
			&i.ExternalQuestionID,
			&i.SelectedAnswerOptionIds,
			&i.IsCorrect,
			&i.Score,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
