// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: child.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChildByIDAndFamilyID = `-- name: GetChildByIDAndFamilyID :one
SELECT id, family_id, first_name, surname, age, gender, profile_image_url, created_at, updated_at, push_notifications_enabled, deleted_at FROM children
WHERE id = $1 AND family_id = $2 AND deleted_at IS NULL
`

type GetChildByIDAndFamilyIDParams struct {
	ID       string `json:"id"`
	FamilyID string `json:"family_id"`
}

func (q *Queries) GetChildByIDAndFamilyID(ctx context.Context, arg GetChildByIDAndFamilyIDParams) (Child, error) {
	row := q.db.QueryRow(ctx, getChildByIDAndFamilyID, arg.ID, arg.FamilyID)
	var i Child
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.FirstName,
		&i.Surname,
		&i.Age,
		&i.Gender,
		&i.ProfileImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushNotificationsEnabled,
		&i.DeletedAt,
	)
	return i, err
}

const updateChild = `-- name: UpdateChild :one
UPDATE children
SET 
    first_name = COALESCE($1, first_name),
    surname = COALESCE($2, surname),
    age = COALESCE($3, age),
    gender = COALESCE($4, gender),
    profile_image_url = COALESCE($5, profile_image_url),
    push_notifications_enabled = COALESCE($6, push_notifications_enabled),
    updated_at = NOW()
WHERE id = $7
RETURNING id, family_id, first_name, surname, age, gender, profile_image_url, created_at, updated_at, push_notifications_enabled, deleted_at
`

type UpdateChildParams struct {
	FirstName                pgtype.Text `json:"first_name"`
	Surname                  pgtype.Text `json:"surname"`
	Age                      pgtype.Int4 `json:"age"`
	Gender                   pgtype.Text `json:"gender"`
	ProfileImageUrl          pgtype.Text `json:"profile_image_url"`
	PushNotificationsEnabled pgtype.Bool `json:"push_notifications_enabled"`
	ID                       string      `json:"id"`
}

func (q *Queries) UpdateChild(ctx context.Context, arg UpdateChildParams) (Child, error) {
	row := q.db.QueryRow(ctx, updateChild,
		arg.FirstName,
		arg.Surname,
		arg.Age,
		arg.Gender,
		arg.ProfileImageUrl,
		arg.PushNotificationsEnabled,
		arg.ID,
	)
	var i Child
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.FirstName,
		&i.Surname,
		&i.Age,
		&i.Gender,
		&i.ProfileImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushNotificationsEnabled,
		&i.DeletedAt,
	)
	return i, err
}
