// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: child_quiz_attempts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkQuizAttemptExistsForChild = `-- name: CheckQuizAttemptExistsForChild :one
SELECT EXISTS (
    SELECT 1
    FROM child_quiz_attempts
    WHERE child_id = $1
)
`

func (q *Queries) CheckQuizAttemptExistsForChild(ctx context.Context, childID string) (bool, error) {
	row := q.db.QueryRow(ctx, checkQuizAttemptExistsForChild, childID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createChildQuizAttempt = `-- name: CreateChildQuizAttempt :one
INSERT INTO child_quiz_attempts (
  child_id,
  course_id,
  module_id,
  external_quiz_id,
  context,
  context_ref,
  attempt_number,
  score,
  passed
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, child_id, course_id, module_id, external_quiz_id, context, context_ref, attempt_number, score, passed, created_at
`

type CreateChildQuizAttemptParams struct {
	ChildID        string         `json:"child_id"`
	CourseID       string         `json:"course_id"`
	ModuleID       string         `json:"module_id"`
	ExternalQuizID string         `json:"external_quiz_id"`
	Context        string         `json:"context"`
	ContextRef     pgtype.Text    `json:"context_ref"`
	AttemptNumber  int32          `json:"attempt_number"`
	Score          pgtype.Numeric `json:"score"`
	Passed         bool           `json:"passed"`
}

func (q *Queries) CreateChildQuizAttempt(ctx context.Context, arg CreateChildQuizAttemptParams) (ChildQuizAttempt, error) {
	row := q.db.QueryRow(ctx, createChildQuizAttempt,
		arg.ChildID,
		arg.CourseID,
		arg.ModuleID,
		arg.ExternalQuizID,
		arg.Context,
		arg.ContextRef,
		arg.AttemptNumber,
		arg.Score,
		arg.Passed,
	)
	var i ChildQuizAttempt
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.CourseID,
		&i.ModuleID,
		&i.ExternalQuizID,
		&i.Context,
		&i.ContextRef,
		&i.AttemptNumber,
		&i.Score,
		&i.Passed,
		&i.CreatedAt,
	)
	return i, err
}

const getChildQuizAttempts = `-- name: GetChildQuizAttempts :many
SELECT id, child_id, course_id, module_id, external_quiz_id, context, context_ref, attempt_number, score, passed, created_at FROM child_quiz_attempts
WHERE child_id = $1 AND course_id = $2 AND module_id = $3 AND external_quiz_id = $4
ORDER BY attempt_number DESC
`

type GetChildQuizAttemptsParams struct {
	ChildID        string `json:"child_id"`
	CourseID       string `json:"course_id"`
	ModuleID       string `json:"module_id"`
	ExternalQuizID string `json:"external_quiz_id"`
}

func (q *Queries) GetChildQuizAttempts(ctx context.Context, arg GetChildQuizAttemptsParams) ([]ChildQuizAttempt, error) {
	rows, err := q.db.Query(ctx, getChildQuizAttempts,
		arg.ChildID,
		arg.CourseID,
		arg.ModuleID,
		arg.ExternalQuizID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChildQuizAttempt{}
	for rows.Next() {
		var i ChildQuizAttempt
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.CourseID,
			&i.ModuleID,
			&i.ExternalQuizID,
			&i.Context,
			&i.ContextRef,
			&i.AttemptNumber,
			&i.Score,
			&i.Passed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
