// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: child_module_progress.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrUpdateModuleProgress = `-- name: CreateOrUpdateModuleProgress :one
INSERT INTO child_module_progress (
  child_id,
  course_id,
  module_id,
  score,
  is_completed,
  feedback_video_url
)
VALUES (
  $1, $2, $3, $4, $5, $6
)
ON CONFLICT (child_id, module_id, course_id)
DO UPDATE SET 
  score = GREATEST(COALESCE(child_module_progress.score, 0), EXCLUDED.score),
  is_completed = child_module_progress.is_completed OR EXCLUDED.is_completed,
  feedback_video_url = EXCLUDED.feedback_video_url,
  last_attempted_at = now()
RETURNING id, child_id, course_id, module_id, score, is_completed, feedback_video_url, last_attempted_at
`

type CreateOrUpdateModuleProgressParams struct {
	ChildID          string         `json:"child_id"`
	CourseID         string         `json:"course_id"`
	ModuleID         string         `json:"module_id"`
	Score            pgtype.Numeric `json:"score"`
	IsCompleted      bool           `json:"is_completed"`
	FeedbackVideoUrl pgtype.Text    `json:"feedback_video_url"`
}

func (q *Queries) CreateOrUpdateModuleProgress(ctx context.Context, arg CreateOrUpdateModuleProgressParams) (ChildModuleProgress, error) {
	row := q.db.QueryRow(ctx, createOrUpdateModuleProgress,
		arg.ChildID,
		arg.CourseID,
		arg.ModuleID,
		arg.Score,
		arg.IsCompleted,
		arg.FeedbackVideoUrl,
	)
	var i ChildModuleProgress
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.CourseID,
		&i.ModuleID,
		&i.Score,
		&i.IsCompleted,
		&i.FeedbackVideoUrl,
		&i.LastAttemptedAt,
	)
	return i, err
}

const getChildModuleProgress = `-- name: GetChildModuleProgress :one
SELECT id, child_id, course_id, module_id, score, is_completed, feedback_video_url, last_attempted_at FROM child_module_progress
WHERE child_id = $1 AND module_id = $2 AND course_id = $3
`

type GetChildModuleProgressParams struct {
	ChildID  string `json:"child_id"`
	ModuleID string `json:"module_id"`
	CourseID string `json:"course_id"`
}

func (q *Queries) GetChildModuleProgress(ctx context.Context, arg GetChildModuleProgressParams) (ChildModuleProgress, error) {
	row := q.db.QueryRow(ctx, getChildModuleProgress, arg.ChildID, arg.ModuleID, arg.CourseID)
	var i ChildModuleProgress
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.CourseID,
		&i.ModuleID,
		&i.Score,
		&i.IsCompleted,
		&i.FeedbackVideoUrl,
		&i.LastAttemptedAt,
	)
	return i, err
}

const getChildModuleProgressForCourse = `-- name: GetChildModuleProgressForCourse :many
SELECT module_id, is_completed FROM child_module_progress
WHERE child_id = $1 AND course_id = $2 AND module_id = ANY($3::text[])
`

type GetChildModuleProgressForCourseParams struct {
	ChildID   string   `json:"child_id"`
	CourseID  string   `json:"course_id"`
	ModuleIds []string `json:"module_ids"`
}

type GetChildModuleProgressForCourseRow struct {
	ModuleID    string `json:"module_id"`
	IsCompleted bool   `json:"is_completed"`
}

func (q *Queries) GetChildModuleProgressForCourse(ctx context.Context, arg GetChildModuleProgressForCourseParams) ([]GetChildModuleProgressForCourseRow, error) {
	rows, err := q.db.Query(ctx, getChildModuleProgressForCourse, arg.ChildID, arg.CourseID, arg.ModuleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChildModuleProgressForCourseRow{}
	for rows.Next() {
		var i GetChildModuleProgressForCourseRow
		if err := rows.Scan(&i.ModuleID, &i.IsCompleted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
