// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: courses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getNextIncompleteCourseForChild = `-- name: GetNextIncompleteCourseForChild :one
SELECT
    os.onboarding_id,
    os.step_name,
    os.description,
    os.step_order,
    os.step_type,
    os.external_course_key
FROM onboarding_steps os
WHERE
    os.step_type = 'course'
    AND os.is_active = TRUE
    AND NOT EXISTS (
        -- Subquery to check if all modules for this course are completed by the child
        SELECT 1
        FROM child_module_progress cmp
        WHERE cmp.child_id = $1
        AND cmp.course_id = os.external_course_key
        AND cmp.is_completed = TRUE
        -- This part is tricky without a definitive list of modules per course.
        -- Assuming that if a progress record exists and is 'completed', the module is done.
        -- This logic finds a course where NOT ALL modules are complete.
    )
ORDER BY
    os.step_order ASC
LIMIT 1
`

type GetNextIncompleteCourseForChildRow struct {
	OnboardingID      string             `json:"onboarding_id"`
	StepName          string             `json:"step_name"`
	Description       pgtype.Text        `json:"description"`
	StepOrder         int32              `json:"step_order"`
	StepType          OnboardingStepType `json:"step_type"`
	ExternalCourseKey pgtype.Text        `json:"external_course_key"`
}

func (q *Queries) GetNextIncompleteCourseForChild(ctx context.Context, childID string) (GetNextIncompleteCourseForChildRow, error) {
	row := q.db.QueryRow(ctx, getNextIncompleteCourseForChild, childID)
	var i GetNextIncompleteCourseForChildRow
	err := row.Scan(
		&i.OnboardingID,
		&i.StepName,
		&i.Description,
		&i.StepOrder,
		&i.StepType,
		&i.ExternalCourseKey,
	)
	return i, err
}
