// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: deep_link_codes.sql

package db

import (
	"context"
	"time"
)

const createDeepLinkCode = `-- name: CreateDeepLinkCode :one
INSERT INTO deep_link_codes (
  family_id,
  child_id,
  code,
  expires_at
) VALUES (
  $1, $2, $3, $4
) RETURNING id, family_id, child_id, code, expires_at, is_used, created_at
`

type CreateDeepLinkCodeParams struct {
	FamilyID  string    `json:"family_id"`
	ChildID   string    `json:"child_id"`
	Code      string    `json:"code"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateDeepLinkCode(ctx context.Context, arg CreateDeepLinkCodeParams) (DeepLinkCode, error) {
	row := q.db.QueryRow(ctx, createDeepLinkCode,
		arg.FamilyID,
		arg.ChildID,
		arg.Code,
		arg.ExpiresAt,
	)
	var i DeepLinkCode
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.ChildID,
		&i.Code,
		&i.ExpiresAt,
		&i.IsUsed,
		&i.CreatedAt,
	)
	return i, err
}

const getDeepLinkCode = `-- name: GetDeepLinkCode :one
SELECT id, family_id, child_id, code, expires_at, is_used, created_at FROM deep_link_codes
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetDeepLinkCode(ctx context.Context, code string) (DeepLinkCode, error) {
	row := q.db.QueryRow(ctx, getDeepLinkCode, code)
	var i DeepLinkCode
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.ChildID,
		&i.Code,
		&i.ExpiresAt,
		&i.IsUsed,
		&i.CreatedAt,
	)
	return i, err
}

const getDeepLinkCodeByChildID = `-- name: GetDeepLinkCodeByChildID :one
SELECT id, family_id, child_id, code, expires_at, is_used, created_at FROM deep_link_codes
WHERE child_id = $1 LIMIT 1
`

func (q *Queries) GetDeepLinkCodeByChildID(ctx context.Context, childID string) (DeepLinkCode, error) {
	row := q.db.QueryRow(ctx, getDeepLinkCodeByChildID, childID)
	var i DeepLinkCode
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.ChildID,
		&i.Code,
		&i.ExpiresAt,
		&i.IsUsed,
		&i.CreatedAt,
	)
	return i, err
}

const updateDeepLinkCode = `-- name: UpdateDeepLinkCode :one
UPDATE deep_link_codes
SET
  code = $2,
  expires_at = $3,
  is_used = FALSE
WHERE id = $1
RETURNING id, family_id, child_id, code, expires_at, is_used, created_at
`

type UpdateDeepLinkCodeParams struct {
	ID        int64     `json:"id"`
	Code      string    `json:"code"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) UpdateDeepLinkCode(ctx context.Context, arg UpdateDeepLinkCodeParams) (DeepLinkCode, error) {
	row := q.db.QueryRow(ctx, updateDeepLinkCode, arg.ID, arg.Code, arg.ExpiresAt)
	var i DeepLinkCode
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.ChildID,
		&i.Code,
		&i.ExpiresAt,
		&i.IsUsed,
		&i.CreatedAt,
	)
	return i, err
}

const useDeepLinkCode = `-- name: UseDeepLinkCode :one
UPDATE deep_link_codes
SET is_used = TRUE
WHERE code = $1
RETURNING id, family_id, child_id, code, expires_at, is_used, created_at
`

func (q *Queries) UseDeepLinkCode(ctx context.Context, code string) (DeepLinkCode, error) {
	row := q.db.QueryRow(ctx, useDeepLinkCode, code)
	var i DeepLinkCode
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.ChildID,
		&i.Code,
		&i.ExpiresAt,
		&i.IsUsed,
		&i.CreatedAt,
	)
	return i, err
}
