// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateDevice = `-- name: ActivateDevice :one
UPDATE devices
SET activated_at = now()
WHERE device_id = $1 AND user_id = $2
RETURNING id, device_id, activated_at, created_at, user_id, user_type, push_token, provider, updated_at
`

type ActivateDeviceParams struct {
	DeviceID string    `json:"device_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) ActivateDevice(ctx context.Context, arg ActivateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, activateDevice, arg.DeviceID, arg.UserID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UserID,
		&i.UserType,
		&i.PushToken,
		&i.Provider,
		&i.UpdatedAt,
	)
	return i, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
  user_id,
  user_type,
  device_id,
  push_token,
  provider
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, device_id, activated_at, created_at, user_id, user_type, push_token, provider, updated_at
`

type CreateDeviceParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	UserType  string      `json:"user_type"`
	DeviceID  string      `json:"device_id"`
	PushToken pgtype.Text `json:"push_token"`
	Provider  pgtype.Text `json:"provider"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.UserID,
		arg.UserType,
		arg.DeviceID,
		arg.PushToken,
		arg.Provider,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UserID,
		&i.UserType,
		&i.PushToken,
		&i.Provider,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateDevicesForUser = `-- name: DeactivateDevicesForUser :exec
UPDATE devices
SET activated_at = NULL
WHERE user_id = $1
`

func (q *Queries) DeactivateDevicesForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateDevicesForUser, userID)
	return err
}

const deactivateUserDevices = `-- name: DeactivateUserDevices :exec
UPDATE devices
SET activated_at = NULL
WHERE user_id = $1 AND activated_at IS NOT NULL
`

func (q *Queries) DeactivateUserDevices(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUserDevices, userID)
	return err
}

const deleteDeviceByID = `-- name: DeleteDeviceByID :exec
DELETE FROM devices
WHERE device_id = $1
`

func (q *Queries) DeleteDeviceByID(ctx context.Context, deviceID string) error {
	_, err := q.db.Exec(ctx, deleteDeviceByID, deviceID)
	return err
}

const getActiveDeviceByDeviceID = `-- name: GetActiveDeviceByDeviceID :one
SELECT id, device_id, activated_at, created_at, user_id, user_type, push_token, provider, updated_at FROM devices
WHERE device_id = $1 AND activated_at IS NOT NULL
`

func (q *Queries) GetActiveDeviceByDeviceID(ctx context.Context, deviceID string) (Device, error) {
	row := q.db.QueryRow(ctx, getActiveDeviceByDeviceID, deviceID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UserID,
		&i.UserType,
		&i.PushToken,
		&i.Provider,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveDeviceByUserAndDeviceID = `-- name: GetActiveDeviceByUserAndDeviceID :one
SELECT id, device_id, activated_at, created_at, user_id, user_type, push_token, provider, updated_at FROM devices
WHERE user_id = $1 AND device_id = $2 AND activated_at IS NOT NULL
`

type GetActiveDeviceByUserAndDeviceIDParams struct {
	UserID   uuid.UUID `json:"user_id"`
	DeviceID string    `json:"device_id"`
}

func (q *Queries) GetActiveDeviceByUserAndDeviceID(ctx context.Context, arg GetActiveDeviceByUserAndDeviceIDParams) (Device, error) {
	row := q.db.QueryRow(ctx, getActiveDeviceByUserAndDeviceID, arg.UserID, arg.DeviceID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UserID,
		&i.UserType,
		&i.PushToken,
		&i.Provider,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceByDeviceID = `-- name: GetDeviceByDeviceID :one
SELECT id, device_id, activated_at, created_at, user_id, user_type, push_token, provider, updated_at FROM devices
WHERE device_id = $1 LIMIT 1
`

func (q *Queries) GetDeviceByDeviceID(ctx context.Context, deviceID string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByDeviceID, deviceID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UserID,
		&i.UserType,
		&i.PushToken,
		&i.Provider,
		&i.UpdatedAt,
	)
	return i, err
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT id, device_id, activated_at, created_at, user_id, user_type, push_token, provider, updated_at FROM devices
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListDevicesByUser(ctx context.Context, userID uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.ActivatedAt,
			&i.CreatedAt,
			&i.UserID,
			&i.UserType,
			&i.PushToken,
			&i.Provider,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushTokensForUser = `-- name: ListPushTokensForUser :many
SELECT push_token FROM devices
WHERE user_id = $1 AND push_token IS NOT NULL
`

func (q *Queries) ListPushTokensForUser(ctx context.Context, userID uuid.UUID) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listPushTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var push_token pgtype.Text
		if err := rows.Scan(&push_token); err != nil {
			return nil, err
		}
		items = append(items, push_token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDevicePushToken = `-- name: UpdateDevicePushToken :one
UPDATE devices
SET 
    push_token = $3,
    provider = $4
WHERE user_id = $1 AND device_id = $2
RETURNING id, device_id, activated_at, created_at, user_id, user_type, push_token, provider, updated_at
`

type UpdateDevicePushTokenParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	DeviceID  string      `json:"device_id"`
	PushToken pgtype.Text `json:"push_token"`
	Provider  pgtype.Text `json:"provider"`
}

func (q *Queries) UpdateDevicePushToken(ctx context.Context, arg UpdateDevicePushTokenParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevicePushToken,
		arg.UserID,
		arg.DeviceID,
		arg.PushToken,
		arg.Provider,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UserID,
		&i.UserType,
		&i.PushToken,
		&i.Provider,
		&i.UpdatedAt,
	)
	return i, err
}
