// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: digital_permit_test.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDigitalPermitTest = `-- name: CreateDigitalPermitTest :one
INSERT INTO digital_permit_tests (
    child_id,
    status,
    started_at
) VALUES (
    $1, 'in_progress', NOW()
) RETURNING id, child_id, status, score, result, started_at, completed_at, created_at, updated_at
`

func (q *Queries) CreateDigitalPermitTest(ctx context.Context, childID string) (DigitalPermitTest, error) {
	row := q.db.QueryRow(ctx, createDigitalPermitTest, childID)
	var i DigitalPermitTest
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.Status,
		&i.Score,
		&i.Result,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDigitalPermitTestInteraction = `-- name: CreateDigitalPermitTestInteraction :one
INSERT INTO digital_permit_test_interactions (
    test_id,
    question_text,
    question_type,
    question_options,
    answer_text,
    points_awarded,
    feedback,
    is_final_question
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, test_id, question_text, question_type, question_options, answer_text, points_awarded, feedback, is_final_question, created_at
`

type CreateDigitalPermitTestInteractionParams struct {
	TestID          uuid.UUID     `json:"test_id"`
	QuestionText    pgtype.Text   `json:"question_text"`
	QuestionType    pgtype.Text   `json:"question_type"`
	QuestionOptions []string      `json:"question_options"`
	AnswerText      pgtype.Text   `json:"answer_text"`
	PointsAwarded   pgtype.Float8 `json:"points_awarded"`
	Feedback        pgtype.Text   `json:"feedback"`
	IsFinalQuestion pgtype.Bool   `json:"is_final_question"`
}

func (q *Queries) CreateDigitalPermitTestInteraction(ctx context.Context, arg CreateDigitalPermitTestInteractionParams) (DigitalPermitTestInteraction, error) {
	row := q.db.QueryRow(ctx, createDigitalPermitTestInteraction,
		arg.TestID,
		arg.QuestionText,
		arg.QuestionType,
		arg.QuestionOptions,
		arg.AnswerText,
		arg.PointsAwarded,
		arg.Feedback,
		arg.IsFinalQuestion,
	)
	var i DigitalPermitTestInteraction
	err := row.Scan(
		&i.ID,
		&i.TestID,
		&i.QuestionText,
		&i.QuestionType,
		&i.QuestionOptions,
		&i.AnswerText,
		&i.PointsAwarded,
		&i.Feedback,
		&i.IsFinalQuestion,
		&i.CreatedAt,
	)
	return i, err
}

const createDigitalPermitTestQuestion = `-- name: CreateDigitalPermitTestQuestion :one
INSERT INTO digital_permit_test_interactions (
    test_id,
    question_text,
    question_type,
    question_options
) VALUES (
    $1, $2, $3, $4
) RETURNING id, test_id, question_text, question_type, question_options, answer_text, points_awarded, feedback, is_final_question, created_at
`

type CreateDigitalPermitTestQuestionParams struct {
	TestID          uuid.UUID   `json:"test_id"`
	QuestionText    pgtype.Text `json:"question_text"`
	QuestionType    pgtype.Text `json:"question_type"`
	QuestionOptions []string    `json:"question_options"`
}

func (q *Queries) CreateDigitalPermitTestQuestion(ctx context.Context, arg CreateDigitalPermitTestQuestionParams) (DigitalPermitTestInteraction, error) {
	row := q.db.QueryRow(ctx, createDigitalPermitTestQuestion,
		arg.TestID,
		arg.QuestionText,
		arg.QuestionType,
		arg.QuestionOptions,
	)
	var i DigitalPermitTestInteraction
	err := row.Scan(
		&i.ID,
		&i.TestID,
		&i.QuestionText,
		&i.QuestionType,
		&i.QuestionOptions,
		&i.AnswerText,
		&i.PointsAwarded,
		&i.Feedback,
		&i.IsFinalQuestion,
		&i.CreatedAt,
	)
	return i, err
}

const getDigitalPermitTestByChildID = `-- name: GetDigitalPermitTestByChildID :one
SELECT id, child_id, status, score, result, started_at, completed_at, created_at, updated_at FROM digital_permit_tests
WHERE child_id = $1 AND status = 'in_progress'
LIMIT 1
`

func (q *Queries) GetDigitalPermitTestByChildID(ctx context.Context, childID string) (DigitalPermitTest, error) {
	row := q.db.QueryRow(ctx, getDigitalPermitTestByChildID, childID)
	var i DigitalPermitTest
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.Status,
		&i.Score,
		&i.Result,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDigitalPermitTestInteractions = `-- name: GetDigitalPermitTestInteractions :many
SELECT id, test_id, question_text, question_type, question_options, answer_text, points_awarded, feedback, is_final_question, created_at
FROM digital_permit_test_interactions
WHERE test_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetDigitalPermitTestInteractions(ctx context.Context, testID uuid.UUID) ([]DigitalPermitTestInteraction, error) {
	rows, err := q.db.Query(ctx, getDigitalPermitTestInteractions, testID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DigitalPermitTestInteraction{}
	for rows.Next() {
		var i DigitalPermitTestInteraction
		if err := rows.Scan(
			&i.ID,
			&i.TestID,
			&i.QuestionText,
			&i.QuestionType,
			&i.QuestionOptions,
			&i.AnswerText,
			&i.PointsAwarded,
			&i.Feedback,
			&i.IsFinalQuestion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestCompletedDigitalPermitTestByChildID = `-- name: GetLatestCompletedDigitalPermitTestByChildID :one
SELECT id, child_id, status, score, result, started_at, completed_at, created_at, updated_at FROM digital_permit_tests
WHERE child_id = $1 AND status = 'completed'
ORDER BY completed_at DESC
LIMIT 1
`

func (q *Queries) GetLatestCompletedDigitalPermitTestByChildID(ctx context.Context, childID string) (DigitalPermitTest, error) {
	row := q.db.QueryRow(ctx, getLatestCompletedDigitalPermitTestByChildID, childID)
	var i DigitalPermitTest
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.Status,
		&i.Score,
		&i.Result,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDigitalPermitTest = `-- name: UpdateDigitalPermitTest :one
UPDATE digital_permit_tests
SET
    status = $2,
    score = $3,
    result = $4,
    completed_at = CASE WHEN $2 = 'completed' THEN NOW() ELSE completed_at END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, child_id, status, score, result, started_at, completed_at, created_at, updated_at
`

type UpdateDigitalPermitTestParams struct {
	ID     uuid.UUID                   `json:"id"`
	Status DigitalPermitTestStatus     `json:"status"`
	Score  float64                     `json:"score"`
	Result NullDigitalPermitTestResult `json:"result"`
}

func (q *Queries) UpdateDigitalPermitTest(ctx context.Context, arg UpdateDigitalPermitTestParams) (DigitalPermitTest, error) {
	row := q.db.QueryRow(ctx, updateDigitalPermitTest,
		arg.ID,
		arg.Status,
		arg.Score,
		arg.Result,
	)
	var i DigitalPermitTest
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.Status,
		&i.Score,
		&i.Result,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDigitalPermitTestInteraction = `-- name: UpdateDigitalPermitTestInteraction :one
UPDATE digital_permit_test_interactions
SET 
    answer_text = $2,
    points_awarded = $3,
    feedback = $4
WHERE id = $1
RETURNING id, test_id, question_text, question_type, question_options, answer_text, points_awarded, feedback, is_final_question, created_at
`

type UpdateDigitalPermitTestInteractionParams struct {
	ID            uuid.UUID     `json:"id"`
	AnswerText    pgtype.Text   `json:"answer_text"`
	PointsAwarded pgtype.Float8 `json:"points_awarded"`
	Feedback      pgtype.Text   `json:"feedback"`
}

func (q *Queries) UpdateDigitalPermitTestInteraction(ctx context.Context, arg UpdateDigitalPermitTestInteractionParams) (DigitalPermitTestInteraction, error) {
	row := q.db.QueryRow(ctx, updateDigitalPermitTestInteraction,
		arg.ID,
		arg.AnswerText,
		arg.PointsAwarded,
		arg.Feedback,
	)
	var i DigitalPermitTestInteraction
	err := row.Scan(
		&i.ID,
		&i.TestID,
		&i.QuestionText,
		&i.QuestionType,
		&i.QuestionOptions,
		&i.AnswerText,
		&i.PointsAwarded,
		&i.Feedback,
		&i.IsFinalQuestion,
		&i.CreatedAt,
	)
	return i, err
}

const updateDigitalPermitTestStatus = `-- name: UpdateDigitalPermitTestStatus :one
UPDATE digital_permit_tests
SET status = $2
WHERE id = $1
RETURNING id, child_id, status, score, result, started_at, completed_at, created_at, updated_at
`

type UpdateDigitalPermitTestStatusParams struct {
	ID     uuid.UUID               `json:"id"`
	Status DigitalPermitTestStatus `json:"status"`
}

func (q *Queries) UpdateDigitalPermitTestStatus(ctx context.Context, arg UpdateDigitalPermitTestStatusParams) (DigitalPermitTest, error) {
	row := q.db.QueryRow(ctx, updateDigitalPermitTestStatus, arg.ID, arg.Status)
	var i DigitalPermitTest
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.Status,
		&i.Score,
		&i.Result,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
