// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: families.sql

package db

import (
	"context"
)

const createFamily = `-- name: CreateFamily :one
INSERT INTO families (
  id,
  private_key,
  public_key
) VALUES (
  $1, $2, $3
) RETURNING id, private_key, public_key, created_at
`

type CreateFamilyParams struct {
	ID         string `json:"id"`
	PrivateKey []byte `json:"private_key"`
	PublicKey  []byte `json:"public_key"`
}

func (q *Queries) CreateFamily(ctx context.Context, arg CreateFamilyParams) (Family, error) {
	row := q.db.QueryRow(ctx, createFamily, arg.ID, arg.PrivateKey, arg.PublicKey)
	var i Family
	err := row.Scan(
		&i.ID,
		&i.PrivateKey,
		&i.PublicKey,
		&i.CreatedAt,
	)
	return i, err
}

const getFamily = `-- name: GetFamily :one
SELECT id, private_key, public_key, created_at FROM families
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFamily(ctx context.Context, id string) (Family, error) {
	row := q.db.QueryRow(ctx, getFamily, id)
	var i Family
	err := row.Scan(
		&i.ID,
		&i.PrivateKey,
		&i.PublicKey,
		&i.CreatedAt,
	)
	return i, err
}
