// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: intentions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDailyIntention = `-- name: CreateDailyIntention :one
INSERT INTO daily_intentions (
  child_id,
  intention_text,
  intention_date,
  time_limit_minutes,
  specific_goals
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, child_id, intention_text, intention_date, time_limit_minutes, specific_goals, is_active, created_at, updated_at
`

type CreateDailyIntentionParams struct {
	ChildID          string      `json:"child_id"`
	IntentionText    string      `json:"intention_text"`
	IntentionDate    pgtype.Date `json:"intention_date"`
	TimeLimitMinutes pgtype.Int4 `json:"time_limit_minutes"`
	SpecificGoals    []byte      `json:"specific_goals"`
}

func (q *Queries) CreateDailyIntention(ctx context.Context, arg CreateDailyIntentionParams) (DailyIntention, error) {
	row := q.db.QueryRow(ctx, createDailyIntention,
		arg.ChildID,
		arg.IntentionText,
		arg.IntentionDate,
		arg.TimeLimitMinutes,
		arg.SpecificGoals,
	)
	var i DailyIntention
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.IntentionText,
		&i.IntentionDate,
		&i.TimeLimitMinutes,
		&i.SpecificGoals,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateIntention = `-- name: DeactivateIntention :exec
UPDATE daily_intentions
SET is_active = false, updated_at = now()
WHERE id = $1
`

func (q *Queries) DeactivateIntention(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateIntention, id)
	return err
}

const deactivateTodayIntentionsForChild = `-- name: DeactivateTodayIntentionsForChild :exec
UPDATE daily_intentions
SET is_active = false, updated_at = now()
WHERE child_id = $1
  AND intention_date = CURRENT_DATE
  AND is_active = true
`

func (q *Queries) DeactivateTodayIntentionsForChild(ctx context.Context, childID string) error {
	_, err := q.db.Exec(ctx, deactivateTodayIntentionsForChild, childID)
	return err
}

const getIntentionByID = `-- name: GetIntentionByID :one
SELECT id, child_id, intention_text, intention_date, time_limit_minutes, specific_goals, is_active, created_at, updated_at FROM daily_intentions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetIntentionByID(ctx context.Context, id uuid.UUID) (DailyIntention, error) {
	row := q.db.QueryRow(ctx, getIntentionByID, id)
	var i DailyIntention
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.IntentionText,
		&i.IntentionDate,
		&i.TimeLimitMinutes,
		&i.SpecificGoals,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntentionHistory = `-- name: GetIntentionHistory :many
SELECT id, child_id, intention_text, intention_date, time_limit_minutes, specific_goals, is_active, created_at, updated_at FROM daily_intentions
WHERE child_id = $1
  AND ($2::date IS NULL OR intention_date >= $2)
  AND ($3::date IS NULL OR intention_date <= $3)
ORDER BY intention_date DESC, created_at DESC
LIMIT $4 OFFSET $5
`

type GetIntentionHistoryParams struct {
	ChildID string      `json:"child_id"`
	Column2 pgtype.Date `json:"column_2"`
	Column3 pgtype.Date `json:"column_3"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) GetIntentionHistory(ctx context.Context, arg GetIntentionHistoryParams) ([]DailyIntention, error) {
	rows, err := q.db.Query(ctx, getIntentionHistory,
		arg.ChildID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyIntention{}
	for rows.Next() {
		var i DailyIntention
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.IntentionText,
			&i.IntentionDate,
			&i.TimeLimitMinutes,
			&i.SpecificGoals,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodayIntention = `-- name: GetTodayIntention :one
SELECT id, child_id, intention_text, intention_date, time_limit_minutes, specific_goals, is_active, created_at, updated_at FROM daily_intentions
WHERE child_id = $1
  AND intention_date = CURRENT_DATE
  AND is_active = true
LIMIT 1
`

func (q *Queries) GetTodayIntention(ctx context.Context, childID string) (DailyIntention, error) {
	row := q.db.QueryRow(ctx, getTodayIntention, childID)
	var i DailyIntention
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.IntentionText,
		&i.IntentionDate,
		&i.TimeLimitMinutes,
		&i.SpecificGoals,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
