// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journal_entries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createJournalEntry = `-- name: CreateJournalEntry :one
INSERT INTO journal_entries (
  child_id,
  entry_date,
  entry_text,
  mood,
  tags,
  media_urls
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, child_id, entry_date, entry_text, mood, tags, media_urls, created_at, updated_at
`

type CreateJournalEntryParams struct {
	ChildID   string      `json:"child_id"`
	EntryDate pgtype.Date `json:"entry_date"`
	EntryText string      `json:"entry_text"`
	Mood      pgtype.Text `json:"mood"`
	Tags      []string    `json:"tags"`
	MediaUrls []string    `json:"media_urls"`
}

func (q *Queries) CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, createJournalEntry,
		arg.ChildID,
		arg.EntryDate,
		arg.EntryText,
		arg.Mood,
		arg.Tags,
		arg.MediaUrls,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.EntryDate,
		&i.EntryText,
		&i.Mood,
		&i.Tags,
		&i.MediaUrls,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJournalEntry = `-- name: DeleteJournalEntry :exec
DELETE FROM journal_entries WHERE id = $1
`

func (q *Queries) DeleteJournalEntry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteJournalEntry, id)
	return err
}

const getJournalEntriesForChild = `-- name: GetJournalEntriesForChild :many
SELECT id, child_id, entry_date, entry_text, mood, tags, media_urls, created_at, updated_at FROM journal_entries
WHERE child_id = $1
  AND ($2::date IS NULL OR entry_date >= $2)
  AND ($3::date IS NULL OR entry_date <= $3)
ORDER BY entry_date DESC, created_at DESC
LIMIT $4 OFFSET $5
`

type GetJournalEntriesForChildParams struct {
	ChildID string      `json:"child_id"`
	Column2 pgtype.Date `json:"column_2"`
	Column3 pgtype.Date `json:"column_3"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) GetJournalEntriesForChild(ctx context.Context, arg GetJournalEntriesForChildParams) ([]JournalEntry, error) {
	rows, err := q.db.Query(ctx, getJournalEntriesForChild,
		arg.ChildID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JournalEntry{}
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.EntryDate,
			&i.EntryText,
			&i.Mood,
			&i.Tags,
			&i.MediaUrls,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJournalEntry = `-- name: GetJournalEntry :one
SELECT id, child_id, entry_date, entry_text, mood, tags, media_urls, created_at, updated_at FROM journal_entries WHERE id = $1 LIMIT 1
`

func (q *Queries) GetJournalEntry(ctx context.Context, id uuid.UUID) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, getJournalEntry, id)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.EntryDate,
		&i.EntryText,
		&i.Mood,
		&i.Tags,
		&i.MediaUrls,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJournalEntryByDate = `-- name: GetJournalEntryByDate :one
SELECT id, child_id, entry_date, entry_text, mood, tags, media_urls, created_at, updated_at FROM journal_entries
WHERE child_id = $1 AND entry_date = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetJournalEntryByDateParams struct {
	ChildID   string      `json:"child_id"`
	EntryDate pgtype.Date `json:"entry_date"`
}

func (q *Queries) GetJournalEntryByDate(ctx context.Context, arg GetJournalEntryByDateParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, getJournalEntryByDate, arg.ChildID, arg.EntryDate)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.EntryDate,
		&i.EntryText,
		&i.Mood,
		&i.Tags,
		&i.MediaUrls,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJournalStats = `-- name: GetJournalStats :one
SELECT
  COUNT(*)                            AS total_entries,
  COUNT(DISTINCT entry_date)          AS active_days,
  COUNT(CASE WHEN mood IS NOT NULL THEN 1 END) AS entries_with_mood,
  MIN(entry_date)                     AS first_entry_date,
  MAX(entry_date)                     AS last_entry_date
FROM journal_entries
WHERE child_id = $1
`

type GetJournalStatsRow struct {
	TotalEntries    int64       `json:"total_entries"`
	ActiveDays      int64       `json:"active_days"`
	EntriesWithMood int64       `json:"entries_with_mood"`
	FirstEntryDate  interface{} `json:"first_entry_date"`
	LastEntryDate   interface{} `json:"last_entry_date"`
}

func (q *Queries) GetJournalStats(ctx context.Context, childID string) (GetJournalStatsRow, error) {
	row := q.db.QueryRow(ctx, getJournalStats, childID)
	var i GetJournalStatsRow
	err := row.Scan(
		&i.TotalEntries,
		&i.ActiveDays,
		&i.EntriesWithMood,
		&i.FirstEntryDate,
		&i.LastEntryDate,
	)
	return i, err
}

const updateJournalEntry = `-- name: UpdateJournalEntry :one
UPDATE journal_entries
SET
  entry_text = $2,
  mood       = $3,
  tags       = $4,
  updated_at = now()
WHERE id = $1
RETURNING id, child_id, entry_date, entry_text, mood, tags, media_urls, created_at, updated_at
`

type UpdateJournalEntryParams struct {
	ID        uuid.UUID   `json:"id"`
	EntryText string      `json:"entry_text"`
	Mood      pgtype.Text `json:"mood"`
	Tags      []string    `json:"tags"`
}

func (q *Queries) UpdateJournalEntry(ctx context.Context, arg UpdateJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, updateJournalEntry,
		arg.ID,
		arg.EntryText,
		arg.Mood,
		arg.Tags,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.EntryDate,
		&i.EntryText,
		&i.Mood,
		&i.Tags,
		&i.MediaUrls,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
