// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthProvider string

const (
	AuthProviderPassword AuthProvider = "password"
	AuthProviderGoogle   AuthProvider = "google"
	AuthProviderApple    AuthProvider = "apple"
)

func (e *AuthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProvider(s)
	case string:
		*e = AuthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProvider: %T", src)
	}
	return nil
}

type NullAuthProvider struct {
	AuthProvider AuthProvider `json:"auth_provider"`
	Valid        bool         `json:"valid"` // Valid is true if AuthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProvider), nil
}

type ChildActivityType string

const (
	ChildActivityTypeCourseStarted              ChildActivityType = "course_started"
	ChildActivityTypeModuleStarted              ChildActivityType = "module_started"
	ChildActivityTypeDigitalPermitTestStarted   ChildActivityType = "digital_permit_test_started"
	ChildActivityTypeDigitalPermitTestCompleted ChildActivityType = "digital_permit_test_completed"
)

func (e *ChildActivityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChildActivityType(s)
	case string:
		*e = ChildActivityType(s)
	default:
		return fmt.Errorf("unsupported scan type for ChildActivityType: %T", src)
	}
	return nil
}

type NullChildActivityType struct {
	ChildActivityType ChildActivityType `json:"child_activity_type"`
	Valid             bool              `json:"valid"` // Valid is true if ChildActivityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChildActivityType) Scan(value interface{}) error {
	if value == nil {
		ns.ChildActivityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChildActivityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChildActivityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChildActivityType), nil
}

type DigitalPermitTestResult string

const (
	DigitalPermitTestResultPass   DigitalPermitTestResult = "pass"
	DigitalPermitTestResultNotYet DigitalPermitTestResult = "not_yet"
)

func (e *DigitalPermitTestResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DigitalPermitTestResult(s)
	case string:
		*e = DigitalPermitTestResult(s)
	default:
		return fmt.Errorf("unsupported scan type for DigitalPermitTestResult: %T", src)
	}
	return nil
}

type NullDigitalPermitTestResult struct {
	DigitalPermitTestResult DigitalPermitTestResult `json:"digital_permit_test_result"`
	Valid                   bool                    `json:"valid"` // Valid is true if DigitalPermitTestResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDigitalPermitTestResult) Scan(value interface{}) error {
	if value == nil {
		ns.DigitalPermitTestResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DigitalPermitTestResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDigitalPermitTestResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DigitalPermitTestResult), nil
}

type DigitalPermitTestStatus string

const (
	DigitalPermitTestStatusNotStarted DigitalPermitTestStatus = "not_started"
	DigitalPermitTestStatusInProgress DigitalPermitTestStatus = "in_progress"
	DigitalPermitTestStatusCompleted  DigitalPermitTestStatus = "completed"
	DigitalPermitTestStatusIncomplete DigitalPermitTestStatus = "incomplete"
)

func (e *DigitalPermitTestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DigitalPermitTestStatus(s)
	case string:
		*e = DigitalPermitTestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DigitalPermitTestStatus: %T", src)
	}
	return nil
}

type NullDigitalPermitTestStatus struct {
	DigitalPermitTestStatus DigitalPermitTestStatus `json:"digital_permit_test_status"`
	Valid                   bool                    `json:"valid"` // Valid is true if DigitalPermitTestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDigitalPermitTestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DigitalPermitTestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DigitalPermitTestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDigitalPermitTestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DigitalPermitTestStatus), nil
}

type NotificationRecipientType string

const (
	NotificationRecipientTypeParent NotificationRecipientType = "parent"
	NotificationRecipientTypeChild  NotificationRecipientType = "child"
)

func (e *NotificationRecipientType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationRecipientType(s)
	case string:
		*e = NotificationRecipientType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationRecipientType: %T", src)
	}
	return nil
}

type NullNotificationRecipientType struct {
	NotificationRecipientType NotificationRecipientType `json:"notification_recipient_type"`
	Valid                     bool                      `json:"valid"` // Valid is true if NotificationRecipientType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationRecipientType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationRecipientType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationRecipientType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationRecipientType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationRecipientType), nil
}

type OnboardingStepType string

const (
	OnboardingStepTypeCourse OnboardingStepType = "course"
	OnboardingStepTypeQuiz   OnboardingStepType = "quiz"
	OnboardingStepTypeAction OnboardingStepType = "action"
)

func (e *OnboardingStepType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OnboardingStepType(s)
	case string:
		*e = OnboardingStepType(s)
	default:
		return fmt.Errorf("unsupported scan type for OnboardingStepType: %T", src)
	}
	return nil
}

type NullOnboardingStepType struct {
	OnboardingStepType OnboardingStepType `json:"onboarding_step_type"`
	Valid              bool               `json:"valid"` // Valid is true if OnboardingStepType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOnboardingStepType) Scan(value interface{}) error {
	if value == nil {
		ns.OnboardingStepType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OnboardingStepType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOnboardingStepType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OnboardingStepType), nil
}

type QuizQuestionType string

const (
	QuizQuestionTypeMultipleChoice QuizQuestionType = "multiple_choice"
	QuizQuestionTypeTrueFalse      QuizQuestionType = "true_false"
	QuizQuestionTypeLongAnswer     QuizQuestionType = "long_answer"
	QuizQuestionTypeReflection     QuizQuestionType = "reflection"
)

func (e *QuizQuestionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuizQuestionType(s)
	case string:
		*e = QuizQuestionType(s)
	default:
		return fmt.Errorf("unsupported scan type for QuizQuestionType: %T", src)
	}
	return nil
}

type NullQuizQuestionType struct {
	QuizQuestionType QuizQuestionType `json:"quiz_question_type"`
	Valid            bool             `json:"valid"` // Valid is true if QuizQuestionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuizQuestionType) Scan(value interface{}) error {
	if value == nil {
		ns.QuizQuestionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuizQuestionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuizQuestionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuizQuestionType), nil
}

type ReflectionResponseType string

const (
	ReflectionResponseTypeText  ReflectionResponseType = "text"
	ReflectionResponseTypeVideo ReflectionResponseType = "video"
	ReflectionResponseTypeAudio ReflectionResponseType = "audio"
)

func (e *ReflectionResponseType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReflectionResponseType(s)
	case string:
		*e = ReflectionResponseType(s)
	default:
		return fmt.Errorf("unsupported scan type for ReflectionResponseType: %T", src)
	}
	return nil
}

type NullReflectionResponseType struct {
	ReflectionResponseType ReflectionResponseType `json:"reflection_response_type"`
	Valid                  bool                   `json:"valid"` // Valid is true if ReflectionResponseType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReflectionResponseType) Scan(value interface{}) error {
	if value == nil {
		ns.ReflectionResponseType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReflectionResponseType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReflectionResponseType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReflectionResponseType), nil
}

type ReflectionTriggerType string

const (
	ReflectionTriggerTypeDailyScheduled ReflectionTriggerType = "daily_scheduled"
	ReflectionTriggerTypePostSession    ReflectionTriggerType = "post_session"
	ReflectionTriggerTypeManual         ReflectionTriggerType = "manual"
)

func (e *ReflectionTriggerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReflectionTriggerType(s)
	case string:
		*e = ReflectionTriggerType(s)
	default:
		return fmt.Errorf("unsupported scan type for ReflectionTriggerType: %T", src)
	}
	return nil
}

type NullReflectionTriggerType struct {
	ReflectionTriggerType ReflectionTriggerType `json:"reflection_trigger_type"`
	Valid                 bool                  `json:"valid"` // Valid is true if ReflectionTriggerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReflectionTriggerType) Scan(value interface{}) error {
	if value == nil {
		ns.ReflectionTriggerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReflectionTriggerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReflectionTriggerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReflectionTriggerType), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusActive   SubscriptionStatus = "active"
	SubscriptionStatusInactive SubscriptionStatus = "inactive"
	SubscriptionStatusPastDue  SubscriptionStatus = "past_due"
	SubscriptionStatusCanceled SubscriptionStatus = "canceled"
)

func (e *SubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionStatus(s)
	case string:
		*e = SubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionStatus: %T", src)
	}
	return nil
}

type NullSubscriptionStatus struct {
	SubscriptionStatus SubscriptionStatus `json:"subscription_status"`
	Valid              bool               `json:"valid"` // Valid is true if SubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionStatus), nil
}

type AccessibleSocialMedium struct {
	ID                     int64              `json:"id"`
	ChildID                string             `json:"child_id"`
	SocialMediaID          int64              `json:"social_media_id"`
	IsAccessible           bool               `json:"is_accessible"`
	AccessRevokedAt        pgtype.Timestamptz `json:"access_revoked_at"`
	SessionDurationSeconds int32              `json:"session_duration_seconds"`
}

type AppSession struct {
	ID              uuid.UUID          `json:"id"`
	ChildID         string             `json:"child_id"`
	SocialMediaID   int64              `json:"social_media_id"`
	StartTime       time.Time          `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	ExpectedEndTime time.Time          `json:"expected_end_time"`
	Status          string             `json:"status"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	LastPingTime    pgtype.Timestamptz `json:"last_ping_time"`
}

type Child struct {
	ID                       string      `json:"id"`
	FamilyID                 string      `json:"family_id"`
	FirstName                string      `json:"first_name"`
	Surname                  string      `json:"surname"`
	Age                      pgtype.Int4 `json:"age"`
	Gender                   pgtype.Text `json:"gender"`
	ProfileImageUrl          pgtype.Text `json:"profile_image_url"`
	CreatedAt                time.Time   `json:"created_at"`
	UpdatedAt                time.Time   `json:"updated_at"`
	PushNotificationsEnabled bool        `json:"push_notifications_enabled"`
}

type ChildActivityLog struct {
	ID            uuid.UUID         `json:"id"`
	ChildID       string            `json:"child_id"`
	ActivityType  ChildActivityType `json:"activity_type"`
	ActivityRefID string            `json:"activity_ref_id"`
	CreatedAt     time.Time         `json:"created_at"`
}

type ChildModuleProgress struct {
	ID               int64              `json:"id"`
	ChildID          string             `json:"child_id"`
	CourseID         string             `json:"course_id"`
	ModuleID         string             `json:"module_id"`
	Score            pgtype.Numeric     `json:"score"`
	IsCompleted      bool               `json:"is_completed"`
	FeedbackVideoUrl pgtype.Text        `json:"feedback_video_url"`
	LastAttemptedAt  pgtype.Timestamptz `json:"last_attempted_at"`
}

type ChildOnboardingProgress struct {
	ID           int64              `json:"id"`
	ChildID      string             `json:"child_id"`
	OnboardingID string             `json:"onboarding_id"`
	IsCompleted  bool               `json:"is_completed"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	CreatedAt    time.Time          `json:"created_at"`
}

type ChildQuizAnswer struct {
	ID                      int64          `json:"id"`
	ChildID                 string         `json:"child_id"`
	CourseID                string         `json:"course_id"`
	ModuleID                string         `json:"module_id"`
	ExternalQuizID          string         `json:"external_quiz_id"`
	AttemptNumber           int32          `json:"attempt_number"`
	ExternalQuestionID      string         `json:"external_question_id"`
	SelectedAnswerOptionIds []string       `json:"selected_answer_option_ids"`
	IsCorrect               bool           `json:"is_correct"`
	Score                   pgtype.Numeric `json:"score"`
	CreatedAt               time.Time      `json:"created_at"`
}

type ChildQuizAttempt struct {
	ID             int64          `json:"id"`
	ChildID        string         `json:"child_id"`
	CourseID       string         `json:"course_id"`
	ModuleID       string         `json:"module_id"`
	ExternalQuizID string         `json:"external_quiz_id"`
	Context        string         `json:"context"`
	ContextRef     pgtype.Text    `json:"context_ref"`
	AttemptNumber  int32          `json:"attempt_number"`
	Score          pgtype.Numeric `json:"score"`
	Passed         bool           `json:"passed"`
	CreatedAt      time.Time      `json:"created_at"`
}

type ChildReflectionContext struct {
	ChildID                    string             `json:"child_id"`
	TotalModulesCompleted      int32              `json:"total_modules_completed"`
	TotalQuizzesTaken          int32              `json:"total_quizzes_taken"`
	AverageQuizScore           pgtype.Numeric     `json:"average_quiz_score"`
	DigitalPermitStatus        pgtype.Text        `json:"digital_permit_status"`
	DigitalPermitScore         pgtype.Numeric     `json:"digital_permit_score"`
	LastActivityDate           pgtype.Timestamptz `json:"last_activity_date"`
	RecentActivities           []byte             `json:"recent_activities"`
	CompletedModuleIds         []string           `json:"completed_module_ids"`
	TotalSmSessions            int32              `json:"total_sm_sessions"`
	AvgDailySmMinutes          pgtype.Numeric     `json:"avg_daily_sm_minutes"`
	MostUsedApps               []byte             `json:"most_used_apps"`
	FrequentContentCategories  []string           `json:"frequent_content_categories"`
	LastSessionEnd             pgtype.Timestamptz `json:"last_session_end"`
	LastReflectionAcknowledged bool               `json:"last_reflection_acknowledged"`
	ReflectionStreak           int32              `json:"reflection_streak"`
	TotalReflectionsResponded  int32              `json:"total_reflections_responded"`
	TotalReflectionsDelivered  int32              `json:"total_reflections_delivered"`
	UpdatedAt                  time.Time          `json:"updated_at"`
}

type ChildWeeklyModule struct {
	ID               int64              `json:"id"`
	ChildID          string             `json:"child_id"`
	ExternalModuleID string             `json:"external_module_id"`
	WeekStartDate    pgtype.Date        `json:"week_start_date"`
	ShownAt          pgtype.Timestamptz `json:"shown_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	LatestScore      pgtype.Numeric     `json:"latest_score"`
	BoosterID        string             `json:"booster_id"`
}

type DailyIntention struct {
	ID               uuid.UUID   `json:"id"`
	ChildID          string      `json:"child_id"`
	IntentionText    string      `json:"intention_text"`
	IntentionDate    pgtype.Date `json:"intention_date"`
	TimeLimitMinutes pgtype.Int4 `json:"time_limit_minutes"`
	SpecificGoals    []byte      `json:"specific_goals"`
	IsActive         bool        `json:"is_active"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type DeepLinkCode struct {
	ID        int64     `json:"id"`
	FamilyID  string    `json:"family_id"`
	ChildID   string    `json:"child_id"`
	Code      string    `json:"code"`
	ExpiresAt time.Time `json:"expires_at"`
	IsUsed    bool      `json:"is_used"`
	CreatedAt time.Time `json:"created_at"`
}

type Device struct {
	ID          int64              `json:"id"`
	DeviceID    string             `json:"device_id"`
	ActivatedAt pgtype.Timestamptz `json:"activated_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UserID      uuid.UUID          `json:"user_id"`
	UserType    string             `json:"user_type"`
	PushToken   pgtype.Text        `json:"push_token"`
	Provider    pgtype.Text        `json:"provider"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type DigitalPermitTest struct {
	ID          uuid.UUID                   `json:"id"`
	ChildID     string                      `json:"child_id"`
	Status      DigitalPermitTestStatus     `json:"status"`
	Score       float64                     `json:"score"`
	Result      NullDigitalPermitTestResult `json:"result"`
	StartedAt   pgtype.Timestamptz          `json:"started_at"`
	CompletedAt pgtype.Timestamptz          `json:"completed_at"`
	CreatedAt   time.Time                   `json:"created_at"`
	UpdatedAt   time.Time                   `json:"updated_at"`
}

type DigitalPermitTestInteraction struct {
	ID              uuid.UUID     `json:"id"`
	TestID          uuid.UUID     `json:"test_id"`
	QuestionText    pgtype.Text   `json:"question_text"`
	QuestionType    pgtype.Text   `json:"question_type"`
	QuestionOptions []string      `json:"question_options"`
	AnswerText      pgtype.Text   `json:"answer_text"`
	PointsAwarded   pgtype.Float8 `json:"points_awarded"`
	Feedback        pgtype.Text   `json:"feedback"`
	IsFinalQuestion pgtype.Bool   `json:"is_final_question"`
	CreatedAt       time.Time     `json:"created_at"`
}

type Family struct {
	ID         string    `json:"id"`
	PrivateKey []byte    `json:"private_key"`
	PublicKey  []byte    `json:"public_key"`
	CreatedAt  time.Time `json:"created_at"`
}

type JournalEntry struct {
	ID        uuid.UUID   `json:"id"`
	ChildID   string      `json:"child_id"`
	EntryDate pgtype.Date `json:"entry_date"`
	EntryText string      `json:"entry_text"`
	Mood      pgtype.Text `json:"mood"`
	Tags      []string    `json:"tags"`
	MediaUrls []string    `json:"media_urls"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type Notification struct {
	ID            uuid.UUID                 `json:"id"`
	RecipientID   uuid.UUID                 `json:"recipient_id"`
	RecipientType NotificationRecipientType `json:"recipient_type"`
	Title         string                    `json:"title"`
	Message       string                    `json:"message"`
	IsRead        bool                      `json:"is_read"`
	SentAt        pgtype.Timestamptz        `json:"sent_at"`
	CreatedAt     time.Time                 `json:"created_at"`
	UpdatedAt     time.Time                 `json:"updated_at"`
}

type OnboardingStep struct {
	OnboardingID      string             `json:"onboarding_id"`
	StepName          string             `json:"step_name"`
	Description       pgtype.Text        `json:"description"`
	StepOrder         int32              `json:"step_order"`
	StepType          OnboardingStepType `json:"step_type"`
	ExternalCourseKey pgtype.Text        `json:"external_course_key"`
	ExternalQuizID    pgtype.Text        `json:"external_quiz_id"`
	RetryLimit        pgtype.Int4        `json:"retry_limit"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

type Parent struct {
	ID                       int64            `json:"id"`
	ParentID                 string           `json:"parent_id"`
	FamilyID                 string           `json:"family_id"`
	Firstname                string           `json:"firstname"`
	Surname                  string           `json:"surname"`
	Email                    string           `json:"email"`
	HashedPassword           pgtype.Text      `json:"hashed_password"`
	AuthProvider             NullAuthProvider `json:"auth_provider"`
	ProviderSubject          pgtype.Text      `json:"provider_subject"`
	EmailVerified            bool             `json:"email_verified"`
	CreatedAt                time.Time        `json:"created_at"`
	UpdatedAt                time.Time        `json:"updated_at"`
	PushNotificationsEnabled bool             `json:"push_notifications_enabled"`
}

type ParentSession struct {
	ID           string    `json:"id"`
	ParentID     string    `json:"parent_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type QuizQuestion struct {
	ID            int64            `json:"id"`
	ModuleID      int64            `json:"module_id"`
	QuestionType  QuizQuestionType `json:"question_type"`
	QuestionText  string           `json:"question_text"`
	Options       []byte           `json:"options"`
	CorrectAnswer pgtype.Text      `json:"correct_answer"`
	Order         int32            `json:"order"`
}

type Receipt struct {
	ID                int64          `json:"id"`
	SubscriptionID    int64          `json:"subscription_id"`
	Amount            pgtype.Numeric `json:"amount"`
	Currency          string         `json:"currency"`
	IssuedAt          time.Time      `json:"issued_at"`
	ProviderReceiptID pgtype.Text    `json:"provider_receipt_id"`
}

type Reflection struct {
	ID                     uuid.UUID                  `json:"id"`
	ChildID                string                     `json:"child_id"`
	TriggerType            ReflectionTriggerType      `json:"trigger_type"`
	TriggerEventID         pgtype.UUID                `json:"trigger_event_id"`
	PromptContent          []byte                     `json:"prompt_content"`
	ResponseText           pgtype.Text                `json:"response_text"`
	ResponseMediaUrl       pgtype.Text                `json:"response_media_url"`
	ResponseType           NullReflectionResponseType `json:"response_type"`
	RespondedAt            pgtype.Timestamptz         `json:"responded_at"`
	IsAcknowledged         bool                       `json:"is_acknowledged"`
	AcknowledgmentFeedback pgtype.Text                `json:"acknowledgment_feedback"`
	DeliveredAt            time.Time                  `json:"delivered_at"`
	Metadata               []byte                     `json:"metadata"`
	CreatedAt              time.Time                  `json:"created_at"`
	UpdatedAt              time.Time                  `json:"updated_at"`
}

type ReflectionVideo struct {
	ID            int64       `json:"id"`
	ChildID       string      `json:"child_id"`
	BoosterID     string      `json:"booster_id"`
	VideoUrl      string      `json:"video_url"`
	StrapiAssetID pgtype.Text `json:"strapi_asset_id"`
	CreatedAt     time.Time   `json:"created_at"`
}

type SocialMedia struct {
	ID      int64       `json:"id"`
	Name    string      `json:"name"`
	IconUrl pgtype.Text `json:"icon_url"`
}

type SocialMediaSession struct {
	ID                  uuid.UUID          `json:"id"`
	ChildID             string             `json:"child_id"`
	SocialMediaID       int64              `json:"social_media_id"`
	IntentionID         pgtype.UUID        `json:"intention_id"`
	SessionStart        time.Time          `json:"session_start"`
	SessionEnd          pgtype.Timestamptz `json:"session_end"`
	DurationMinutes     pgtype.Int4        `json:"duration_minutes"`
	ContentCategories   []string           `json:"content_categories"`
	InteractionCount    int32              `json:"interaction_count"`
	ReflectionTriggered bool               `json:"reflection_triggered"`
	ReflectionID        pgtype.UUID        `json:"reflection_id"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
}

type SocialMediaUsageStat struct {
	ID              int64     `json:"id"`
	ChildID         string    `json:"child_id"`
	SocialMediaID   int64     `json:"social_media_id"`
	StartTime       time.Time `json:"start_time"`
	EndTime         time.Time `json:"end_time"`
	DurationSeconds int32     `json:"duration_seconds"`
}

type Subscription struct {
	ID                     int64              `json:"id"`
	FamilyID               string             `json:"family_id"`
	Provider               string             `json:"provider"`
	ProviderSubscriptionID string             `json:"provider_subscription_id"`
	Status                 SubscriptionStatus `json:"status"`
	Plan                   string             `json:"plan"`
	CurrentPeriodEnd       time.Time          `json:"current_period_end"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
}

type WeeklyModuleSchedule struct {
	ID            int64       `json:"id"`
	ModuleID      int64       `json:"module_id"`
	WeekStartDate pgtype.Date `json:"week_start_date"`
	IsActive      bool        `json:"is_active"`
}
