// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
  recipient_id,
  recipient_type,
  title,
  message,
  sent_at
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, recipient_id, recipient_type, title, message, is_read, sent_at, created_at, updated_at
`

type CreateNotificationParams struct {
	RecipientID   uuid.UUID                 `json:"recipient_id"`
	RecipientType NotificationRecipientType `json:"recipient_type"`
	Title         string                    `json:"title"`
	Message       string                    `json:"message"`
	SentAt        pgtype.Timestamptz        `json:"sent_at"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.RecipientID,
		arg.RecipientType,
		arg.Title,
		arg.Message,
		arg.SentAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.RecipientType,
		&i.Title,
		&i.Message,
		&i.IsRead,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationsForRecipient = `-- name: GetNotificationsForRecipient :many
SELECT id, recipient_id, recipient_type, title, message, is_read, sent_at, created_at, updated_at FROM notifications
WHERE recipient_id = $1 AND recipient_type = $2
ORDER BY created_at DESC
`

type GetNotificationsForRecipientParams struct {
	RecipientID   uuid.UUID                 `json:"recipient_id"`
	RecipientType NotificationRecipientType `json:"recipient_type"`
}

func (q *Queries) GetNotificationsForRecipient(ctx context.Context, arg GetNotificationsForRecipientParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getNotificationsForRecipient, arg.RecipientID, arg.RecipientType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.RecipientType,
			&i.Title,
			&i.Message,
			&i.IsRead,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :one
UPDATE notifications
SET is_read = TRUE
WHERE id = $1 AND recipient_id = $2
RETURNING id, recipient_id, recipient_type, title, message, is_read, sent_at, created_at, updated_at
`

type MarkNotificationAsReadParams struct {
	ID          uuid.UUID `json:"id"`
	RecipientID uuid.UUID `json:"recipient_id"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationAsRead, arg.ID, arg.RecipientID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.RecipientType,
		&i.Title,
		&i.Message,
		&i.IsRead,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
