// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: onboarding.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChildOnboardingProgress = `-- name: CreateChildOnboardingProgress :exec
INSERT INTO child_onboarding_progress (child_id, onboarding_id)
SELECT $1, onboarding_id FROM onboarding_steps WHERE is_active = true
`

func (q *Queries) CreateChildOnboardingProgress(ctx context.Context, childID string) error {
	_, err := q.db.Exec(ctx, createChildOnboardingProgress, childID)
	return err
}

const createOnboardingStep = `-- name: CreateOnboardingStep :one
INSERT INTO onboarding_steps (
  step_name,
  description,
  step_order
) VALUES (
  $1, $2, $3
) RETURNING onboarding_id, step_name, description, step_order, step_type, external_course_key, external_quiz_id, retry_limit, is_active, created_at, updated_at
`

type CreateOnboardingStepParams struct {
	StepName    string      `json:"step_name"`
	Description pgtype.Text `json:"description"`
	StepOrder   int32       `json:"step_order"`
}

func (q *Queries) CreateOnboardingStep(ctx context.Context, arg CreateOnboardingStepParams) (OnboardingStep, error) {
	row := q.db.QueryRow(ctx, createOnboardingStep, arg.StepName, arg.Description, arg.StepOrder)
	var i OnboardingStep
	err := row.Scan(
		&i.OnboardingID,
		&i.StepName,
		&i.Description,
		&i.StepOrder,
		&i.StepType,
		&i.ExternalCourseKey,
		&i.ExternalQuizID,
		&i.RetryLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOnboardingStep = `-- name: DeleteOnboardingStep :exec
DELETE FROM onboarding_steps
WHERE onboarding_id = $1
`

func (q *Queries) DeleteOnboardingStep(ctx context.Context, onboardingID string) error {
	_, err := q.db.Exec(ctx, deleteOnboardingStep, onboardingID)
	return err
}

const getChildOnboardingProgress = `-- name: GetChildOnboardingProgress :many
SELECT os.step_name, os.description, os.step_order, os.step_type, cop.is_completed, cop.completed_at
FROM child_onboarding_progress cop
JOIN onboarding_steps os ON cop.onboarding_id = os.onboarding_id
WHERE cop.child_id = $1
ORDER BY os.step_order
`

type GetChildOnboardingProgressRow struct {
	StepName    string             `json:"step_name"`
	Description pgtype.Text        `json:"description"`
	StepOrder   int32              `json:"step_order"`
	StepType    OnboardingStepType `json:"step_type"`
	IsCompleted bool               `json:"is_completed"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) GetChildOnboardingProgress(ctx context.Context, childID string) ([]GetChildOnboardingProgressRow, error) {
	rows, err := q.db.Query(ctx, getChildOnboardingProgress, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChildOnboardingProgressRow{}
	for rows.Next() {
		var i GetChildOnboardingProgressRow
		if err := rows.Scan(
			&i.StepName,
			&i.Description,
			&i.StepOrder,
			&i.StepType,
			&i.IsCompleted,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOnboardingProgressByFamilyID = `-- name: GetOnboardingProgressByFamilyID :many
SELECT 
    c.id as child_id,
    os.step_name,
    os.description,
    os.step_order,
    os.step_type,
    cop.is_completed,
    cop.completed_at
FROM children c
JOIN child_onboarding_progress cop ON c.id = cop.child_id
JOIN onboarding_steps os ON cop.onboarding_id = os.onboarding_id
WHERE c.family_id = $1
ORDER BY c.id, os.step_order
`

type GetOnboardingProgressByFamilyIDRow struct {
	ChildID     string             `json:"child_id"`
	StepName    string             `json:"step_name"`
	Description pgtype.Text        `json:"description"`
	StepOrder   int32              `json:"step_order"`
	StepType    OnboardingStepType `json:"step_type"`
	IsCompleted bool               `json:"is_completed"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) GetOnboardingProgressByFamilyID(ctx context.Context, familyID string) ([]GetOnboardingProgressByFamilyIDRow, error) {
	rows, err := q.db.Query(ctx, getOnboardingProgressByFamilyID, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOnboardingProgressByFamilyIDRow{}
	for rows.Next() {
		var i GetOnboardingProgressByFamilyIDRow
		if err := rows.Scan(
			&i.ChildID,
			&i.StepName,
			&i.Description,
			&i.StepOrder,
			&i.StepType,
			&i.IsCompleted,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOnboardingStep = `-- name: GetOnboardingStep :one
SELECT onboarding_id, step_name, description, step_order, step_type, external_course_key, external_quiz_id, retry_limit, is_active, created_at, updated_at FROM onboarding_steps
WHERE onboarding_id = $1
`

func (q *Queries) GetOnboardingStep(ctx context.Context, onboardingID string) (OnboardingStep, error) {
	row := q.db.QueryRow(ctx, getOnboardingStep, onboardingID)
	var i OnboardingStep
	err := row.Scan(
		&i.OnboardingID,
		&i.StepName,
		&i.Description,
		&i.StepOrder,
		&i.StepType,
		&i.ExternalCourseKey,
		&i.ExternalQuizID,
		&i.RetryLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOnboardingStepByOrder = `-- name: GetOnboardingStepByOrder :one
SELECT onboarding_id, step_name, description, step_order, step_type, external_course_key, external_quiz_id, retry_limit, is_active, created_at, updated_at FROM onboarding_steps
WHERE step_order = $1
`

func (q *Queries) GetOnboardingStepByOrder(ctx context.Context, stepOrder int32) (OnboardingStep, error) {
	row := q.db.QueryRow(ctx, getOnboardingStepByOrder, stepOrder)
	var i OnboardingStep
	err := row.Scan(
		&i.OnboardingID,
		&i.StepName,
		&i.Description,
		&i.StepOrder,
		&i.StepType,
		&i.ExternalCourseKey,
		&i.ExternalQuizID,
		&i.RetryLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveOnboardingSteps = `-- name: ListActiveOnboardingSteps :many
SELECT onboarding_id, step_name, description, step_order, step_type, external_course_key, external_quiz_id, retry_limit, is_active, created_at, updated_at FROM onboarding_steps
WHERE is_active = true
ORDER BY step_order
`

func (q *Queries) ListActiveOnboardingSteps(ctx context.Context) ([]OnboardingStep, error) {
	rows, err := q.db.Query(ctx, listActiveOnboardingSteps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OnboardingStep{}
	for rows.Next() {
		var i OnboardingStep
		if err := rows.Scan(
			&i.OnboardingID,
			&i.StepName,
			&i.Description,
			&i.StepOrder,
			&i.StepType,
			&i.ExternalCourseKey,
			&i.ExternalQuizID,
			&i.RetryLimit,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChildOnboardingStep = `-- name: UpdateChildOnboardingStep :one
UPDATE child_onboarding_progress
SET is_completed = true, completed_at = now()
WHERE child_id = $1 AND onboarding_id = $2
RETURNING id, child_id, onboarding_id, is_completed, completed_at, created_at
`

type UpdateChildOnboardingStepParams struct {
	ChildID      string `json:"child_id"`
	OnboardingID string `json:"onboarding_id"`
}

func (q *Queries) UpdateChildOnboardingStep(ctx context.Context, arg UpdateChildOnboardingStepParams) (ChildOnboardingProgress, error) {
	row := q.db.QueryRow(ctx, updateChildOnboardingStep, arg.ChildID, arg.OnboardingID)
	var i ChildOnboardingProgress
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.OnboardingID,
		&i.IsCompleted,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateOnboardingStep = `-- name: UpdateOnboardingStep :one
UPDATE onboarding_steps
SET
  step_name = COALESCE($1, step_name),
  description = COALESCE($2, description),
  step_order = COALESCE($3, step_order),
  is_active = COALESCE($4, is_active)
WHERE
  onboarding_id = $5
RETURNING onboarding_id, step_name, description, step_order, step_type, external_course_key, external_quiz_id, retry_limit, is_active, created_at, updated_at
`

type UpdateOnboardingStepParams struct {
	StepName     pgtype.Text `json:"step_name"`
	Description  pgtype.Text `json:"description"`
	StepOrder    pgtype.Int4 `json:"step_order"`
	IsActive     pgtype.Bool `json:"is_active"`
	OnboardingID string      `json:"onboarding_id"`
}

func (q *Queries) UpdateOnboardingStep(ctx context.Context, arg UpdateOnboardingStepParams) (OnboardingStep, error) {
	row := q.db.QueryRow(ctx, updateOnboardingStep,
		arg.StepName,
		arg.Description,
		arg.StepOrder,
		arg.IsActive,
		arg.OnboardingID,
	)
	var i OnboardingStep
	err := row.Scan(
		&i.OnboardingID,
		&i.StepName,
		&i.Description,
		&i.StepOrder,
		&i.StepType,
		&i.ExternalCourseKey,
		&i.ExternalQuizID,
		&i.RetryLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
