// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parent_sessions.sql

package db

import (
	"context"
	"time"
)

const createParentSession = `-- name: CreateParentSession :one
INSERT INTO parent_sessions (
  id,
  parent_id,
  refresh_token,
  user_agent,
  client_ip,
  is_blocked,
  expires_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, parent_id, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at
`

type CreateParentSessionParams struct {
	ID           string    `json:"id"`
	ParentID     string    `json:"parent_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) CreateParentSession(ctx context.Context, arg CreateParentSessionParams) (ParentSession, error) {
	row := q.db.QueryRow(ctx, createParentSession,
		arg.ID,
		arg.ParentID,
		arg.RefreshToken,
		arg.UserAgent,
		arg.ClientIp,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	var i ParentSession
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getParentSession = `-- name: GetParentSession :one
SELECT id, parent_id, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at FROM parent_sessions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetParentSession(ctx context.Context, id string) (ParentSession, error) {
	row := q.db.QueryRow(ctx, getParentSession, id)
	var i ParentSession
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
