// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: parent.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChildForParent = `-- name: GetChildForParent :one
SELECT c.id, c.family_id, c.first_name, c.surname, c.age, c.gender, c.profile_image_url, c.created_at, c.updated_at, c.push_notifications_enabled FROM children c
JOIN parents p ON c.family_id = p.family_id
WHERE p.parent_id = $1 AND c.id = $2
`

type GetChildForParentParams struct {
	ParentID string `json:"parent_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetChildForParent(ctx context.Context, arg GetChildForParentParams) (Child, error) {
	row := q.db.QueryRow(ctx, getChildForParent, arg.ParentID, arg.ID)
	var i Child
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.FirstName,
		&i.Surname,
		&i.Age,
		&i.Gender,
		&i.ProfileImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushNotificationsEnabled,
	)
	return i, err
}

const updateParent = `-- name: UpdateParent :one
UPDATE parents
SET
  firstname = COALESCE($1, firstname),
  surname = COALESCE($2, surname),
  push_notifications_enabled = COALESCE($3, push_notifications_enabled),
  updated_at = now()
WHERE
  parent_id = $4
RETURNING id, parent_id, family_id, firstname, surname, email, hashed_password, auth_provider, provider_subject, email_verified, created_at, updated_at, push_notifications_enabled
`

type UpdateParentParams struct {
	Firstname                pgtype.Text `json:"firstname"`
	Surname                  pgtype.Text `json:"surname"`
	PushNotificationsEnabled pgtype.Bool `json:"push_notifications_enabled"`
	ParentID                 string      `json:"parent_id"`
}

func (q *Queries) UpdateParent(ctx context.Context, arg UpdateParentParams) (Parent, error) {
	row := q.db.QueryRow(ctx, updateParent,
		arg.Firstname,
		arg.Surname,
		arg.PushNotificationsEnabled,
		arg.ParentID,
	)
	var i Parent
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.FamilyID,
		&i.Firstname,
		&i.Surname,
		&i.Email,
		&i.HashedPassword,
		&i.AuthProvider,
		&i.ProviderSubject,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushNotificationsEnabled,
	)
	return i, err
}
