// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: parent_daily_insights.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createParentDailyInsight = `-- name: CreateParentDailyInsight :one
INSERT INTO parent_daily_insights (
  parent_id,
  child_id,
  date,
  insight_content,
  overall_tone
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, parent_id, child_id, date, insight_content, overall_tone, is_read, generated_at, created_at
`

type CreateParentDailyInsightParams struct {
	ParentID       string      `json:"parent_id"`
	ChildID        string      `json:"child_id"`
	Date           pgtype.Date `json:"date"`
	InsightContent []byte      `json:"insight_content"`
	OverallTone    string      `json:"overall_tone"`
}

func (q *Queries) CreateParentDailyInsight(ctx context.Context, arg CreateParentDailyInsightParams) (ParentDailyInsight, error) {
	row := q.db.QueryRow(ctx, createParentDailyInsight,
		arg.ParentID,
		arg.ChildID,
		arg.Date,
		arg.InsightContent,
		arg.OverallTone,
	)
	var i ParentDailyInsight
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.ChildID,
		&i.Date,
		&i.InsightContent,
		&i.OverallTone,
		&i.IsRead,
		&i.GeneratedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAllChildrenForParentInsightScheduler = `-- name: GetAllChildrenForParentInsightScheduler :many
SELECT DISTINCT p.parent_id, c.id AS child_id
FROM parents p
JOIN children c ON c.family_id = p.family_id
WHERE NOT EXISTS (
    SELECT 1 FROM parent_daily_insights pdi
    WHERE pdi.parent_id = p.parent_id
      AND pdi.child_id  = c.id
      AND pdi.date      = CURRENT_DATE
  )
`

type GetAllChildrenForParentInsightSchedulerRow struct {
	ParentID string `json:"parent_id"`
	ChildID  string `json:"child_id"`
}

// Returns distinct (parent_id, child_id) pairs that do NOT yet have an insight
// row for today. Used by the nightly cron to determine what to generate.
func (q *Queries) GetAllChildrenForParentInsightScheduler(ctx context.Context) ([]GetAllChildrenForParentInsightSchedulerRow, error) {
	rows, err := q.db.Query(ctx, getAllChildrenForParentInsightScheduler)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllChildrenForParentInsightSchedulerRow{}
	for rows.Next() {
		var i GetAllChildrenForParentInsightSchedulerRow
		if err := rows.Scan(&i.ParentID, &i.ChildID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParentInsightHistory = `-- name: GetParentInsightHistory :many
SELECT id, parent_id, child_id, date, insight_content, overall_tone, is_read, generated_at, created_at FROM parent_daily_insights
WHERE parent_id = $1
  AND child_id  = $2
ORDER BY date DESC
LIMIT  $3
OFFSET $4
`

type GetParentInsightHistoryParams struct {
	ParentID string `json:"parent_id"`
	ChildID  string `json:"child_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) GetParentInsightHistory(ctx context.Context, arg GetParentInsightHistoryParams) ([]ParentDailyInsight, error) {
	rows, err := q.db.Query(ctx, getParentInsightHistory,
		arg.ParentID,
		arg.ChildID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParentDailyInsight{}
	for rows.Next() {
		var i ParentDailyInsight
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.ChildID,
			&i.Date,
			&i.InsightContent,
			&i.OverallTone,
			&i.IsRead,
			&i.GeneratedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodayParentInsightForChild = `-- name: GetTodayParentInsightForChild :one
SELECT id, parent_id, child_id, date, insight_content, overall_tone, is_read, generated_at, created_at FROM parent_daily_insights
WHERE parent_id = $1
  AND child_id  = $2
  AND date      = CURRENT_DATE
LIMIT 1
`

type GetTodayParentInsightForChildParams struct {
	ParentID string `json:"parent_id"`
	ChildID  string `json:"child_id"`
}

func (q *Queries) GetTodayParentInsightForChild(ctx context.Context, arg GetTodayParentInsightForChildParams) (ParentDailyInsight, error) {
	row := q.db.QueryRow(ctx, getTodayParentInsightForChild, arg.ParentID, arg.ChildID)
	var i ParentDailyInsight
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.ChildID,
		&i.Date,
		&i.InsightContent,
		&i.OverallTone,
		&i.IsRead,
		&i.GeneratedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markParentInsightRead = `-- name: MarkParentInsightRead :one
UPDATE parent_daily_insights
SET is_read = true
WHERE id        = $1
  AND parent_id = $2
RETURNING id, parent_id, child_id, date, insight_content, overall_tone, is_read, generated_at, created_at
`

type MarkParentInsightReadParams struct {
	ID       uuid.UUID `json:"id"`
	ParentID string    `json:"parent_id"`
}

func (q *Queries) MarkParentInsightRead(ctx context.Context, arg MarkParentInsightReadParams) (ParentDailyInsight, error) {
	row := q.db.QueryRow(ctx, markParentInsightRead, arg.ID, arg.ParentID)
	var i ParentDailyInsight
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.ChildID,
		&i.Date,
		&i.InsightContent,
		&i.OverallTone,
		&i.IsRead,
		&i.GeneratedAt,
		&i.CreatedAt,
	)
	return i, err
}
