// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: parents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createParent = `-- name: CreateParent :one
INSERT INTO parents (
  parent_id,
  family_id,
  firstname,
  surname,
  email,
  hashed_password,
  auth_provider,
  provider_subject,
  email_verified
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, parent_id, family_id, firstname, surname, email, hashed_password, auth_provider, provider_subject, email_verified, created_at, updated_at, push_notifications_enabled
`

type CreateParentParams struct {
	ParentID        string           `json:"parent_id"`
	FamilyID        string           `json:"family_id"`
	Firstname       string           `json:"firstname"`
	Surname         string           `json:"surname"`
	Email           string           `json:"email"`
	HashedPassword  pgtype.Text      `json:"hashed_password"`
	AuthProvider    NullAuthProvider `json:"auth_provider"`
	ProviderSubject pgtype.Text      `json:"provider_subject"`
	EmailVerified   bool             `json:"email_verified"`
}

func (q *Queries) CreateParent(ctx context.Context, arg CreateParentParams) (Parent, error) {
	row := q.db.QueryRow(ctx, createParent,
		arg.ParentID,
		arg.FamilyID,
		arg.Firstname,
		arg.Surname,
		arg.Email,
		arg.HashedPassword,
		arg.AuthProvider,
		arg.ProviderSubject,
		arg.EmailVerified,
	)
	var i Parent
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.FamilyID,
		&i.Firstname,
		&i.Surname,
		&i.Email,
		&i.HashedPassword,
		&i.AuthProvider,
		&i.ProviderSubject,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushNotificationsEnabled,
	)
	return i, err
}

const getParentByEmail = `-- name: GetParentByEmail :one
SELECT id, parent_id, family_id, firstname, surname, email, hashed_password, auth_provider, provider_subject, email_verified, created_at, updated_at, push_notifications_enabled FROM parents
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetParentByEmail(ctx context.Context, email string) (Parent, error) {
	row := q.db.QueryRow(ctx, getParentByEmail, email)
	var i Parent
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.FamilyID,
		&i.Firstname,
		&i.Surname,
		&i.Email,
		&i.HashedPassword,
		&i.AuthProvider,
		&i.ProviderSubject,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushNotificationsEnabled,
	)
	return i, err
}

const getParentByFamilyID = `-- name: GetParentByFamilyID :one
SELECT id, parent_id, family_id, firstname, surname, email, hashed_password, auth_provider, provider_subject, email_verified, created_at, updated_at, push_notifications_enabled FROM parents
WHERE family_id = $1
LIMIT 1
`

func (q *Queries) GetParentByFamilyID(ctx context.Context, familyID string) (Parent, error) {
	row := q.db.QueryRow(ctx, getParentByFamilyID, familyID)
	var i Parent
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.FamilyID,
		&i.Firstname,
		&i.Surname,
		&i.Email,
		&i.HashedPassword,
		&i.AuthProvider,
		&i.ProviderSubject,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushNotificationsEnabled,
	)
	return i, err
}

const getParentByParentID = `-- name: GetParentByParentID :one
SELECT id, parent_id, family_id, firstname, surname, email, hashed_password, auth_provider, provider_subject, email_verified, created_at, updated_at, push_notifications_enabled FROM parents
WHERE parent_id = $1 LIMIT 1
`

func (q *Queries) GetParentByParentID(ctx context.Context, parentID string) (Parent, error) {
	row := q.db.QueryRow(ctx, getParentByParentID, parentID)
	var i Parent
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.FamilyID,
		&i.Firstname,
		&i.Surname,
		&i.Email,
		&i.HashedPassword,
		&i.AuthProvider,
		&i.ProviderSubject,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushNotificationsEnabled,
	)
	return i, err
}

const getParentByProvider = `-- name: GetParentByProvider :one
SELECT id, parent_id, family_id, firstname, surname, email, hashed_password, auth_provider, provider_subject, email_verified, created_at, updated_at, push_notifications_enabled FROM parents
WHERE auth_provider = $1 AND provider_subject = $2 LIMIT 1
`

type GetParentByProviderParams struct {
	AuthProvider    NullAuthProvider `json:"auth_provider"`
	ProviderSubject pgtype.Text      `json:"provider_subject"`
}

func (q *Queries) GetParentByProvider(ctx context.Context, arg GetParentByProviderParams) (Parent, error) {
	row := q.db.QueryRow(ctx, getParentByProvider, arg.AuthProvider, arg.ProviderSubject)
	var i Parent
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.FamilyID,
		&i.Firstname,
		&i.Surname,
		&i.Email,
		&i.HashedPassword,
		&i.AuthProvider,
		&i.ProviderSubject,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushNotificationsEnabled,
	)
	return i, err
}

const linkParentProvider = `-- name: LinkParentProvider :one
UPDATE parents
SET 
  provider_subject = $2,
  auth_provider = $3,
  email_verified = $4,
  updated_at = now()
WHERE id = $1
RETURNING id, parent_id, family_id, firstname, surname, email, hashed_password, auth_provider, provider_subject, email_verified, created_at, updated_at, push_notifications_enabled
`

type LinkParentProviderParams struct {
	ID              int64            `json:"id"`
	ProviderSubject pgtype.Text      `json:"provider_subject"`
	AuthProvider    NullAuthProvider `json:"auth_provider"`
	EmailVerified   bool             `json:"email_verified"`
}

func (q *Queries) LinkParentProvider(ctx context.Context, arg LinkParentProviderParams) (Parent, error) {
	row := q.db.QueryRow(ctx, linkParentProvider,
		arg.ID,
		arg.ProviderSubject,
		arg.AuthProvider,
		arg.EmailVerified,
	)
	var i Parent
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.FamilyID,
		&i.Firstname,
		&i.Surname,
		&i.Email,
		&i.HashedPassword,
		&i.AuthProvider,
		&i.ProviderSubject,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushNotificationsEnabled,
	)
	return i, err
}
