// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quiz_questions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuizQuestion = `-- name: CreateQuizQuestion :one
INSERT INTO quiz_questions (
  module_id,
  question_type,
  question_text,
  options,
  correct_answer,
  "order"
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, module_id, question_type, question_text, options, correct_answer, "order"
`

type CreateQuizQuestionParams struct {
	ModuleID      int64            `json:"module_id"`
	QuestionType  QuizQuestionType `json:"question_type"`
	QuestionText  string           `json:"question_text"`
	Options       []byte           `json:"options"`
	CorrectAnswer pgtype.Text      `json:"correct_answer"`
	Order         int32            `json:"order"`
}

func (q *Queries) CreateQuizQuestion(ctx context.Context, arg CreateQuizQuestionParams) (QuizQuestion, error) {
	row := q.db.QueryRow(ctx, createQuizQuestion,
		arg.ModuleID,
		arg.QuestionType,
		arg.QuestionText,
		arg.Options,
		arg.CorrectAnswer,
		arg.Order,
	)
	var i QuizQuestion
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.QuestionType,
		&i.QuestionText,
		&i.Options,
		&i.CorrectAnswer,
		&i.Order,
	)
	return i, err
}

const listQuestionsByModule = `-- name: ListQuestionsByModule :many
SELECT id, module_id, question_type, question_text, options, correct_answer, "order" FROM quiz_questions
WHERE module_id = $1
ORDER BY "order"
`

func (q *Queries) ListQuestionsByModule(ctx context.Context, moduleID int64) ([]QuizQuestion, error) {
	rows, err := q.db.Query(ctx, listQuestionsByModule, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuizQuestion{}
	for rows.Next() {
		var i QuizQuestion
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.QuestionType,
			&i.QuestionText,
			&i.Options,
			&i.CorrectAnswer,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
