// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: receipts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReceipt = `-- name: CreateReceipt :one
INSERT INTO receipts (
  subscription_id,
  amount,
  currency,
  provider_receipt_id
) VALUES (
  $1, $2, $3, $4
) RETURNING id, subscription_id, amount, currency, issued_at, provider_receipt_id
`

type CreateReceiptParams struct {
	SubscriptionID    int64          `json:"subscription_id"`
	Amount            pgtype.Numeric `json:"amount"`
	Currency          string         `json:"currency"`
	ProviderReceiptID pgtype.Text    `json:"provider_receipt_id"`
}

func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error) {
	row := q.db.QueryRow(ctx, createReceipt,
		arg.SubscriptionID,
		arg.Amount,
		arg.Currency,
		arg.ProviderReceiptID,
	)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.Amount,
		&i.Currency,
		&i.IssuedAt,
		&i.ProviderReceiptID,
	)
	return i, err
}

const listReceiptsBySubscription = `-- name: ListReceiptsBySubscription :many
SELECT id, subscription_id, amount, currency, issued_at, provider_receipt_id FROM receipts
WHERE subscription_id = $1
ORDER BY issued_at DESC
`

func (q *Queries) ListReceiptsBySubscription(ctx context.Context, subscriptionID int64) ([]Receipt, error) {
	rows, err := q.db.Query(ctx, listReceiptsBySubscription, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Receipt{}
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.Amount,
			&i.Currency,
			&i.IssuedAt,
			&i.ProviderReceiptID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
