// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reflections.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeReflection = `-- name: AcknowledgeReflection :exec
UPDATE reflections
SET
  is_acknowledged         = true,
  acknowledgment_feedback = $2,
  updated_at              = now()
WHERE id = $1
`

type AcknowledgeReflectionParams struct {
	ID                     uuid.UUID   `json:"id"`
	AcknowledgmentFeedback pgtype.Text `json:"acknowledgment_feedback"`
}

func (q *Queries) AcknowledgeReflection(ctx context.Context, arg AcknowledgeReflectionParams) error {
	_, err := q.db.Exec(ctx, acknowledgeReflection, arg.ID, arg.AcknowledgmentFeedback)
	return err
}

const countPostSessionReflectionsToday = `-- name: CountPostSessionReflectionsToday :one
SELECT COUNT(*) FROM reflections
WHERE child_id = $1
  AND trigger_type = 'post_session'
  AND DATE(delivered_at) = CURRENT_DATE
`

func (q *Queries) CountPostSessionReflectionsToday(ctx context.Context, childID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPostSessionReflectionsToday, childID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReflection = `-- name: CreateReflection :one
INSERT INTO reflections (
  child_id,
  trigger_type,
  trigger_event_id,
  prompt_content,
  metadata
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, child_id, trigger_type, trigger_event_id, prompt_content, response_text, response_media_url, response_type, responded_at, is_acknowledged, acknowledgment_feedback, delivered_at, metadata, created_at, updated_at
`

type CreateReflectionParams struct {
	ChildID        string                `json:"child_id"`
	TriggerType    ReflectionTriggerType `json:"trigger_type"`
	TriggerEventID pgtype.UUID           `json:"trigger_event_id"`
	PromptContent  []byte                `json:"prompt_content"`
	Metadata       []byte                `json:"metadata"`
}

func (q *Queries) CreateReflection(ctx context.Context, arg CreateReflectionParams) (Reflection, error) {
	row := q.db.QueryRow(ctx, createReflection,
		arg.ChildID,
		arg.TriggerType,
		arg.TriggerEventID,
		arg.PromptContent,
		arg.Metadata,
	)
	var i Reflection
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.TriggerType,
		&i.TriggerEventID,
		&i.PromptContent,
		&i.ResponseText,
		&i.ResponseMediaUrl,
		&i.ResponseType,
		&i.RespondedAt,
		&i.IsAcknowledged,
		&i.AcknowledgmentFeedback,
		&i.DeliveredAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTimedSessionReflection = `-- name: CreateTimedSessionReflection :one
INSERT INTO reflections (
  child_id,
  trigger_type,
  prompt_content,
  metadata
) VALUES (
  $1, $2, $3, $4
) RETURNING id, child_id, trigger_type, trigger_event_id, prompt_content, response_text, response_media_url, response_type, responded_at, is_acknowledged, acknowledgment_feedback, delivered_at, metadata, created_at, updated_at
`

type CreateTimedSessionReflectionParams struct {
	ChildID       string                `json:"child_id"`
	TriggerType   ReflectionTriggerType `json:"trigger_type"`
	PromptContent []byte                `json:"prompt_content"`
	Metadata      []byte                `json:"metadata"`
}

func (q *Queries) CreateTimedSessionReflection(ctx context.Context, arg CreateTimedSessionReflectionParams) (Reflection, error) {
	row := q.db.QueryRow(ctx, createTimedSessionReflection,
		arg.ChildID,
		arg.TriggerType,
		arg.PromptContent,
		arg.Metadata,
	)
	var i Reflection
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.TriggerType,
		&i.TriggerEventID,
		&i.PromptContent,
		&i.ResponseText,
		&i.ResponseMediaUrl,
		&i.ResponseType,
		&i.RespondedAt,
		&i.IsAcknowledged,
		&i.AcknowledgmentFeedback,
		&i.DeliveredAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChildrenNeedingDailyReflection = `-- name: GetChildrenNeedingDailyReflection :many
SELECT c.id AS child_id, c.first_name, c.age
FROM children c
WHERE c.age >= 13
  AND NOT EXISTS (
    SELECT 1 FROM reflections r
    WHERE r.child_id = c.id
      AND r.trigger_type = 'daily_scheduled'
      AND DATE(r.delivered_at) = CURRENT_DATE
  )
`

type GetChildrenNeedingDailyReflectionRow struct {
	ChildID   string      `json:"child_id"`
	FirstName string      `json:"first_name"`
	Age       pgtype.Int4 `json:"age"`
}

func (q *Queries) GetChildrenNeedingDailyReflection(ctx context.Context) ([]GetChildrenNeedingDailyReflectionRow, error) {
	rows, err := q.db.Query(ctx, getChildrenNeedingDailyReflection)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChildrenNeedingDailyReflectionRow{}
	for rows.Next() {
		var i GetChildrenNeedingDailyReflectionRow
		if err := rows.Scan(&i.ChildID, &i.FirstName, &i.Age); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllEligibleChildrenForReflection = `-- name: GetAllEligibleChildrenForReflection :many
SELECT c.id AS child_id, c.first_name, c.age
FROM children c
WHERE c.age >= 13
`

func (q *Queries) GetAllEligibleChildrenForReflection(ctx context.Context) ([]GetChildrenNeedingDailyReflectionRow, error) {
	rows, err := q.db.Query(ctx, getAllEligibleChildrenForReflection)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChildrenNeedingDailyReflectionRow{}
	for rows.Next() {
		var i GetChildrenNeedingDailyReflectionRow
		if err := rows.Scan(&i.ChildID, &i.FirstName, &i.Age); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingReflectionsForChild = `-- name: GetPendingReflectionsForChild :many
SELECT id, child_id, trigger_type, trigger_event_id, prompt_content, response_text, response_media_url, response_type, responded_at, is_acknowledged, acknowledgment_feedback, delivered_at, metadata, created_at, updated_at FROM reflections
WHERE child_id = $1
  AND responded_at IS NULL
ORDER BY delivered_at DESC
LIMIT $2 OFFSET $3
`

type GetPendingReflectionsForChildParams struct {
	ChildID string `json:"child_id"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) GetPendingReflectionsForChild(ctx context.Context, arg GetPendingReflectionsForChildParams) ([]Reflection, error) {
	rows, err := q.db.Query(ctx, getPendingReflectionsForChild, arg.ChildID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reflection{}
	for rows.Next() {
		var i Reflection
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.TriggerType,
			&i.TriggerEventID,
			&i.PromptContent,
			&i.ResponseText,
			&i.ResponseMediaUrl,
			&i.ResponseType,
			&i.RespondedAt,
			&i.IsAcknowledged,
			&i.AcknowledgmentFeedback,
			&i.DeliveredAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentReflectionsForChild = `-- name: GetRecentReflectionsForChild :many
SELECT id, child_id, trigger_type, trigger_event_id, prompt_content, response_text, response_media_url, response_type, responded_at, is_acknowledged, acknowledgment_feedback, delivered_at, metadata, created_at, updated_at FROM reflections
WHERE child_id = $1
ORDER BY delivered_at DESC
LIMIT $2
`

type GetRecentReflectionsForChildParams struct {
	ChildID string `json:"child_id"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) GetRecentReflectionsForChild(ctx context.Context, arg GetRecentReflectionsForChildParams) ([]Reflection, error) {
	rows, err := q.db.Query(ctx, getRecentReflectionsForChild, arg.ChildID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reflection{}
	for rows.Next() {
		var i Reflection
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.TriggerType,
			&i.TriggerEventID,
			&i.PromptContent,
			&i.ResponseText,
			&i.ResponseMediaUrl,
			&i.ResponseType,
			&i.RespondedAt,
			&i.IsAcknowledged,
			&i.AcknowledgmentFeedback,
			&i.DeliveredAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentDailyReflectionsWithResponses = `-- name: GetRecentDailyReflectionsWithResponses :many
SELECT prompt_content, response_text, delivered_at
FROM reflections
WHERE child_id = $1
  AND trigger_type = 'daily_scheduled'
  AND responded_at IS NOT NULL
ORDER BY delivered_at DESC
LIMIT 10
`

type GetRecentDailyReflectionsWithResponsesRow struct {
	PromptContent []byte      `json:"prompt_content"`
	ResponseText  pgtype.Text `json:"response_text"`
	DeliveredAt   time.Time   `json:"delivered_at"`
}

func (q *Queries) GetRecentDailyReflectionsWithResponses(ctx context.Context, childID string) ([]GetRecentDailyReflectionsWithResponsesRow, error) {
	rows, err := q.db.Query(ctx, getRecentDailyReflectionsWithResponses, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentDailyReflectionsWithResponsesRow{}
	for rows.Next() {
		var i GetRecentDailyReflectionsWithResponsesRow
		if err := rows.Scan(&i.PromptContent, &i.ResponseText, &i.DeliveredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReflection = `-- name: GetReflection :one
SELECT id, child_id, trigger_type, trigger_event_id, prompt_content, response_text, response_media_url, response_type, responded_at, is_acknowledged, acknowledgment_feedback, delivered_at, metadata, created_at, updated_at FROM reflections WHERE id = $1 LIMIT 1
`

func (q *Queries) GetReflection(ctx context.Context, id uuid.UUID) (Reflection, error) {
	row := q.db.QueryRow(ctx, getReflection, id)
	var i Reflection
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.TriggerType,
		&i.TriggerEventID,
		&i.PromptContent,
		&i.ResponseText,
		&i.ResponseMediaUrl,
		&i.ResponseType,
		&i.RespondedAt,
		&i.IsAcknowledged,
		&i.AcknowledgmentFeedback,
		&i.DeliveredAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReflectionHistory = `-- name: GetReflectionHistory :many
SELECT id, child_id, trigger_type, trigger_event_id, prompt_content, response_text, response_media_url, response_type, responded_at, is_acknowledged, acknowledgment_feedback, delivered_at, metadata, created_at, updated_at FROM reflections
WHERE child_id = $1
  AND ($2::reflection_trigger_type IS NULL OR trigger_type = $2)
  AND ($3::boolean IS NULL OR responded_at IS NOT NULL = $3)
  AND ($4::timestamptz IS NULL OR delivered_at >= $4)
  AND ($5::timestamptz IS NULL OR delivered_at <= $5)
ORDER BY delivered_at DESC
LIMIT $6 OFFSET $7
`

type GetReflectionHistoryParams struct {
	ChildID string                 `json:"child_id"`
	Column2 *ReflectionTriggerType `json:"column_2"`
	Column3 bool                   `json:"column_3"`
	Column4 time.Time              `json:"column_4"`
	Column5 time.Time              `json:"column_5"`
	Limit   int32                  `json:"limit"`
	Offset  int32                  `json:"offset"`
}

func (q *Queries) GetReflectionHistory(ctx context.Context, arg GetReflectionHistoryParams) ([]Reflection, error) {
	rows, err := q.db.Query(ctx, getReflectionHistory,
		arg.ChildID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reflection{}
	for rows.Next() {
		var i Reflection
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.TriggerType,
			&i.TriggerEventID,
			&i.PromptContent,
			&i.ResponseText,
			&i.ResponseMediaUrl,
			&i.ResponseType,
			&i.RespondedAt,
			&i.IsAcknowledged,
			&i.AcknowledgmentFeedback,
			&i.DeliveredAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReflectionStats = `-- name: GetReflectionStats :one
SELECT
  COUNT(*)                                                                AS total_reflections,
  COUNT(CASE WHEN responded_at IS NOT NULL THEN 1 END)                   AS total_responded,
  COUNT(CASE WHEN is_acknowledged = true THEN 1 END)                     AS total_acknowledged,
  COUNT(CASE WHEN trigger_type = 'daily_scheduled' THEN 1 END)           AS total_daily,
  COUNT(CASE WHEN trigger_type = 'post_session' THEN 1 END)              AS total_post_session,
  AVG(EXTRACT(EPOCH FROM (responded_at - delivered_at))/60)::numeric(10,2) AS avg_response_time_minutes
FROM reflections
WHERE child_id = $1
  AND ($2::timestamptz IS NULL OR delivered_at >= $2)
  AND ($3::timestamptz IS NULL OR delivered_at <= $3)
`

type GetReflectionStatsParams struct {
	ChildID string    `json:"child_id"`
	Column2 time.Time `json:"column_2"`
	Column3 time.Time `json:"column_3"`
}

type GetReflectionStatsRow struct {
	TotalReflections       int64          `json:"total_reflections"`
	TotalResponded         int64          `json:"total_responded"`
	TotalAcknowledged      int64          `json:"total_acknowledged"`
	TotalDaily             int64          `json:"total_daily"`
	TotalPostSession       int64          `json:"total_post_session"`
	AvgResponseTimeMinutes pgtype.Numeric `json:"avg_response_time_minutes"`
}

func (q *Queries) GetReflectionStats(ctx context.Context, arg GetReflectionStatsParams) (GetReflectionStatsRow, error) {
	row := q.db.QueryRow(ctx, getReflectionStats, arg.ChildID, arg.Column2, arg.Column3)
	var i GetReflectionStatsRow
	err := row.Scan(
		&i.TotalReflections,
		&i.TotalResponded,
		&i.TotalAcknowledged,
		&i.TotalDaily,
		&i.TotalPostSession,
		&i.AvgResponseTimeMinutes,
	)
	return i, err
}

const getTodayDailyReflectionForChild = `-- name: GetTodayDailyReflectionForChild :one
SELECT id, child_id, trigger_type, trigger_event_id, prompt_content, response_text, response_media_url, response_type, responded_at, is_acknowledged, acknowledgment_feedback, delivered_at, metadata, created_at, updated_at FROM reflections
WHERE child_id = $1
  AND trigger_type = 'daily_scheduled'
  AND DATE(delivered_at) = CURRENT_DATE
ORDER BY delivered_at DESC
LIMIT 1
`

func (q *Queries) GetTodayDailyReflectionForChild(ctx context.Context, childID string) (Reflection, error) {
	row := q.db.QueryRow(ctx, getTodayDailyReflectionForChild, childID)
	var i Reflection
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.TriggerType,
		&i.TriggerEventID,
		&i.PromptContent,
		&i.ResponseText,
		&i.ResponseMediaUrl,
		&i.ResponseType,
		&i.RespondedAt,
		&i.IsAcknowledged,
		&i.AcknowledgmentFeedback,
		&i.DeliveredAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReflectionMediaResponse = `-- name: UpdateReflectionMediaResponse :one
UPDATE reflections
SET
  response_media_url = $2,
  response_type      = $3,
  responded_at       = now(),
  updated_at         = now()
WHERE id = $1
RETURNING id, child_id, trigger_type, trigger_event_id, prompt_content, response_text, response_media_url, response_type, responded_at, is_acknowledged, acknowledgment_feedback, delivered_at, metadata, created_at, updated_at
`

type UpdateReflectionMediaResponseParams struct {
	ID               uuid.UUID                  `json:"id"`
	ResponseMediaUrl pgtype.Text                `json:"response_media_url"`
	ResponseType     NullReflectionResponseType `json:"response_type"`
}

func (q *Queries) UpdateReflectionMediaResponse(ctx context.Context, arg UpdateReflectionMediaResponseParams) (Reflection, error) {
	row := q.db.QueryRow(ctx, updateReflectionMediaResponse, arg.ID, arg.ResponseMediaUrl, arg.ResponseType)
	var i Reflection
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.TriggerType,
		&i.TriggerEventID,
		&i.PromptContent,
		&i.ResponseText,
		&i.ResponseMediaUrl,
		&i.ResponseType,
		&i.RespondedAt,
		&i.IsAcknowledged,
		&i.AcknowledgmentFeedback,
		&i.DeliveredAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReflectionTextResponse = `-- name: UpdateReflectionTextResponse :one
UPDATE reflections
SET
  response_text  = $2,
  response_type  = $3,
  responded_at   = now(),
  updated_at     = now()
WHERE id = $1
RETURNING id, child_id, trigger_type, trigger_event_id, prompt_content, response_text, response_media_url, response_type, responded_at, is_acknowledged, acknowledgment_feedback, delivered_at, metadata, created_at, updated_at
`

type UpdateReflectionTextResponseParams struct {
	ID           uuid.UUID                  `json:"id"`
	ResponseText pgtype.Text                `json:"response_text"`
	ResponseType NullReflectionResponseType `json:"response_type"`
}

func (q *Queries) UpdateReflectionTextResponse(ctx context.Context, arg UpdateReflectionTextResponseParams) (Reflection, error) {
	row := q.db.QueryRow(ctx, updateReflectionTextResponse, arg.ID, arg.ResponseText, arg.ResponseType)
	var i Reflection
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.TriggerType,
		&i.TriggerEventID,
		&i.PromptContent,
		&i.ResponseText,
		&i.ResponseMediaUrl,
		&i.ResponseType,
		&i.RespondedAt,
		&i.IsAcknowledged,
		&i.AcknowledgmentFeedback,
		&i.DeliveredAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
