// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: reflection_videos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReflectionVideo = `-- name: CreateReflectionVideo :one
INSERT INTO reflection_videos (
  child_id,
  booster_id,
  video_url,
  strapi_asset_id
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, child_id, booster_id, video_url, strapi_asset_id, created_at
`

type CreateReflectionVideoParams struct {
	ChildID       string      `json:"child_id"`
	BoosterID     string      `json:"booster_id"`
	VideoUrl      string      `json:"video_url"`
	StrapiAssetID pgtype.Text `json:"strapi_asset_id"`
}

func (q *Queries) CreateReflectionVideo(ctx context.Context, arg CreateReflectionVideoParams) (ReflectionVideo, error) {
	row := q.db.QueryRow(ctx, createReflectionVideo,
		arg.ChildID,
		arg.BoosterID,
		arg.VideoUrl,
		arg.StrapiAssetID,
	)
	var i ReflectionVideo
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.BoosterID,
		&i.VideoUrl,
		&i.StrapiAssetID,
		&i.CreatedAt,
	)
	return i, err
}

const getReflectionVideo = `-- name: GetReflectionVideo :one
SELECT id, child_id, booster_id, video_url, strapi_asset_id, created_at FROM reflection_videos
WHERE child_id = $1 AND booster_id = $2
`

type GetReflectionVideoParams struct {
	ChildID   string `json:"child_id"`
	BoosterID string `json:"booster_id"`
}

func (q *Queries) GetReflectionVideo(ctx context.Context, arg GetReflectionVideoParams) (ReflectionVideo, error) {
	row := q.db.QueryRow(ctx, getReflectionVideo, arg.ChildID, arg.BoosterID)
	var i ReflectionVideo
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.BoosterID,
		&i.VideoUrl,
		&i.StrapiAssetID,
		&i.CreatedAt,
	)
	return i, err
}
