// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: social_medias.sql

package db

import (
	"context"
)

const listSocialMedias = `-- name: ListSocialMedias :many
SELECT id, name, icon_url FROM social_medias
`

func (q *Queries) ListSocialMedias(ctx context.Context) ([]SocialMedia, error) {
	rows, err := q.db.Query(ctx, listSocialMedias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SocialMedia{}
	for rows.Next() {
		var i SocialMedia
		if err := rows.Scan(&i.ID, &i.Name, &i.IconUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
