// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: social_media_sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSocialMediaSession = `-- name: CreateSocialMediaSession :one
INSERT INTO social_media_sessions (
  child_id,
  social_media_id,
  intention_id,
  session_start,
  content_categories,
  interaction_count
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, child_id, social_media_id, intention_id, session_start, session_end, duration_minutes, content_categories, interaction_count, reflection_triggered, reflection_id, created_at, updated_at
`

type CreateSocialMediaSessionParams struct {
	ChildID           string      `json:"child_id"`
	SocialMediaID     int64       `json:"social_media_id"`
	IntentionID       pgtype.UUID `json:"intention_id"`
	SessionStart      time.Time   `json:"session_start"`
	ContentCategories []string    `json:"content_categories"`
	InteractionCount  int32       `json:"interaction_count"`
}

func (q *Queries) CreateSocialMediaSession(ctx context.Context, arg CreateSocialMediaSessionParams) (SocialMediaSession, error) {
	row := q.db.QueryRow(ctx, createSocialMediaSession,
		arg.ChildID,
		arg.SocialMediaID,
		arg.IntentionID,
		arg.SessionStart,
		arg.ContentCategories,
		arg.InteractionCount,
	)
	var i SocialMediaSession
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.SocialMediaID,
		&i.IntentionID,
		&i.SessionStart,
		&i.SessionEnd,
		&i.DurationMinutes,
		&i.ContentCategories,
		&i.InteractionCount,
		&i.ReflectionTriggered,
		&i.ReflectionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endSocialMediaSession = `-- name: EndSocialMediaSession :one
UPDATE social_media_sessions
SET
  session_end        = now(),
  duration_minutes   = GREATEST(1, EXTRACT(EPOCH FROM (now() - session_start))::int / 60),
  content_categories = CASE WHEN array_length($2::text[], 1) > 0 THEN $2::text[] ELSE content_categories END,
  interaction_count  = CASE WHEN $3::int > 0 THEN $3::int ELSE interaction_count END,
  updated_at         = now()
WHERE id = $1
RETURNING id, child_id, social_media_id, intention_id, session_start, session_end, duration_minutes, content_categories, interaction_count, reflection_triggered, reflection_id, created_at, updated_at
`

type EndSocialMediaSessionParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 []string  `json:"column_2"`
	Column3 int32     `json:"column_3"`
}

func (q *Queries) EndSocialMediaSession(ctx context.Context, arg EndSocialMediaSessionParams) (SocialMediaSession, error) {
	row := q.db.QueryRow(ctx, endSocialMediaSession, arg.ID, arg.Column2, arg.Column3)
	var i SocialMediaSession
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.SocialMediaID,
		&i.IntentionID,
		&i.SessionStart,
		&i.SessionEnd,
		&i.DurationMinutes,
		&i.ContentCategories,
		&i.InteractionCount,
		&i.ReflectionTriggered,
		&i.ReflectionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveSocialMediaSession = `-- name: GetActiveSocialMediaSession :one
SELECT id, child_id, social_media_id, intention_id, session_start, session_end, duration_minutes, content_categories, interaction_count, reflection_triggered, reflection_id, created_at, updated_at FROM social_media_sessions
WHERE child_id = $1
  AND social_media_id = $2
  AND session_end IS NULL
ORDER BY session_start DESC
LIMIT 1
`

type GetActiveSocialMediaSessionParams struct {
	ChildID       string `json:"child_id"`
	SocialMediaID int64  `json:"social_media_id"`
}

func (q *Queries) GetActiveSocialMediaSession(ctx context.Context, arg GetActiveSocialMediaSessionParams) (SocialMediaSession, error) {
	row := q.db.QueryRow(ctx, getActiveSocialMediaSession, arg.ChildID, arg.SocialMediaID)
	var i SocialMediaSession
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.SocialMediaID,
		&i.IntentionID,
		&i.SessionStart,
		&i.SessionEnd,
		&i.DurationMinutes,
		&i.ContentCategories,
		&i.InteractionCount,
		&i.ReflectionTriggered,
		&i.ReflectionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDailyUsageStats = `-- name: GetDailyUsageStats :many
SELECT
  DATE(session_start)              AS usage_date,
  SUM(duration_minutes)::int       AS total_minutes,
  COUNT(*)                         AS session_count,
  array_agg(DISTINCT social_media_id) AS apps_used
FROM social_media_sessions
WHERE child_id      = $1
  AND session_start >= $2
  AND session_start <= $3
  AND session_end IS NOT NULL
GROUP BY DATE(session_start)
ORDER BY usage_date DESC
`

type GetDailyUsageStatsParams struct {
	ChildID        string    `json:"child_id"`
	SessionStart   time.Time `json:"session_start"`
	SessionStart_2 time.Time `json:"session_start_2"`
}

type GetDailyUsageStatsRow struct {
	UsageDate    pgtype.Date `json:"usage_date"`
	TotalMinutes int32       `json:"total_minutes"`
	SessionCount int64       `json:"session_count"`
	AppsUsed     interface{} `json:"apps_used"`
}

func (q *Queries) GetDailyUsageStats(ctx context.Context, arg GetDailyUsageStatsParams) ([]GetDailyUsageStatsRow, error) {
	rows, err := q.db.Query(ctx, getDailyUsageStats, arg.ChildID, arg.SessionStart, arg.SessionStart_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyUsageStatsRow{}
	for rows.Next() {
		var i GetDailyUsageStatsRow
		if err := rows.Scan(
			&i.UsageDate,
			&i.TotalMinutes,
			&i.SessionCount,
			&i.AppsUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentSessionsNeedingReflection = `-- name: GetRecentSessionsNeedingReflection :many
SELECT id, child_id, social_media_id, intention_id, session_start, session_end, duration_minutes, content_categories, interaction_count, reflection_triggered, reflection_id, created_at, updated_at FROM social_media_sessions
WHERE child_id = $1
  AND session_end IS NOT NULL
  AND reflection_triggered = false
  AND session_end >= now() - INTERVAL '2 hours'
ORDER BY session_end DESC
`

func (q *Queries) GetRecentSessionsNeedingReflection(ctx context.Context, childID string) ([]SocialMediaSession, error) {
	rows, err := q.db.Query(ctx, getRecentSessionsNeedingReflection, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SocialMediaSession{}
	for rows.Next() {
		var i SocialMediaSession
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.SocialMediaID,
			&i.IntentionID,
			&i.SessionStart,
			&i.SessionEnd,
			&i.DurationMinutes,
			&i.ContentCategories,
			&i.InteractionCount,
			&i.ReflectionTriggered,
			&i.ReflectionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionsByChild = `-- name: GetSessionsByChild :many
SELECT id, child_id, social_media_id, intention_id, session_start, session_end, duration_minutes, content_categories, interaction_count, reflection_triggered, reflection_id, created_at, updated_at FROM social_media_sessions
WHERE child_id = $1
ORDER BY session_start DESC
LIMIT $2 OFFSET $3
`

type GetSessionsByChildParams struct {
	ChildID string `json:"child_id"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) GetSessionsByChild(ctx context.Context, arg GetSessionsByChildParams) ([]SocialMediaSession, error) {
	rows, err := q.db.Query(ctx, getSessionsByChild, arg.ChildID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SocialMediaSession{}
	for rows.Next() {
		var i SocialMediaSession
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.SocialMediaID,
			&i.IntentionID,
			&i.SessionStart,
			&i.SessionEnd,
			&i.DurationMinutes,
			&i.ContentCategories,
			&i.InteractionCount,
			&i.ReflectionTriggered,
			&i.ReflectionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSocialMediaSession = `-- name: GetSocialMediaSession :one
SELECT id, child_id, social_media_id, intention_id, session_start, session_end, duration_minutes, content_categories, interaction_count, reflection_triggered, reflection_id, created_at, updated_at FROM social_media_sessions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSocialMediaSession(ctx context.Context, id uuid.UUID) (SocialMediaSession, error) {
	row := q.db.QueryRow(ctx, getSocialMediaSession, id)
	var i SocialMediaSession
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.SocialMediaID,
		&i.IntentionID,
		&i.SessionStart,
		&i.SessionEnd,
		&i.DurationMinutes,
		&i.ContentCategories,
		&i.InteractionCount,
		&i.ReflectionTriggered,
		&i.ReflectionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSessionReflectionTriggered = `-- name: MarkSessionReflectionTriggered :exec
UPDATE social_media_sessions
SET
  reflection_triggered = true,
  reflection_id        = $2,
  updated_at           = now()
WHERE id = $1
`

type MarkSessionReflectionTriggeredParams struct {
	ID           uuid.UUID   `json:"id"`
	ReflectionID pgtype.UUID `json:"reflection_id"`
}

func (q *Queries) MarkSessionReflectionTriggered(ctx context.Context, arg MarkSessionReflectionTriggeredParams) error {
	_, err := q.db.Exec(ctx, markSessionReflectionTriggered, arg.ID, arg.ReflectionID)
	return err
}
