// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: social_media_usage_stats.sql

package db

import (
	"context"
	"time"
)

const getSocialMediaUsageForChild = `-- name: GetSocialMediaUsageForChild :many
SELECT
  sm.name AS platform,
  SUM(s.duration_seconds) AS total_duration
FROM social_media_usage_stats s
JOIN social_medias sm ON s.social_media_id = sm.id
WHERE s.child_id = $1 AND s.start_time >= $2
GROUP BY sm.name
`

type GetSocialMediaUsageForChildParams struct {
	ChildID   string    `json:"child_id"`
	StartTime time.Time `json:"start_time"`
}

type GetSocialMediaUsageForChildRow struct {
	Platform      string `json:"platform"`
	TotalDuration int64  `json:"total_duration"`
}

func (q *Queries) GetSocialMediaUsageForChild(ctx context.Context, arg GetSocialMediaUsageForChildParams) ([]GetSocialMediaUsageForChildRow, error) {
	rows, err := q.db.Query(ctx, getSocialMediaUsageForChild, arg.ChildID, arg.StartTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSocialMediaUsageForChildRow{}
	for rows.Next() {
		var i GetSocialMediaUsageForChildRow
		if err := rows.Scan(&i.Platform, &i.TotalDuration); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logSocialMediaUsage = `-- name: LogSocialMediaUsage :one
INSERT INTO social_media_usage_stats (
  child_id,
  social_media_id,
  start_time,
  end_time,
  duration_seconds
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, child_id, social_media_id, start_time, end_time, duration_seconds
`

type LogSocialMediaUsageParams struct {
	ChildID         string    `json:"child_id"`
	SocialMediaID   int64     `json:"social_media_id"`
	StartTime       time.Time `json:"start_time"`
	EndTime         time.Time `json:"end_time"`
	DurationSeconds int32     `json:"duration_seconds"`
}

func (q *Queries) LogSocialMediaUsage(ctx context.Context, arg LogSocialMediaUsageParams) (SocialMediaUsageStat, error) {
	row := q.db.QueryRow(ctx, logSocialMediaUsage,
		arg.ChildID,
		arg.SocialMediaID,
		arg.StartTime,
		arg.EndTime,
		arg.DurationSeconds,
	)
	var i SocialMediaUsageStat
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.SocialMediaID,
		&i.StartTime,
		&i.EndTime,
		&i.DurationSeconds,
	)
	return i, err
}
