// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: subscriptions.sql

package db

import (
	"context"
	"time"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
  family_id,
  provider,
  provider_subscription_id,
  status,
  plan,
  current_period_end
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, family_id, provider, provider_subscription_id, status, plan, current_period_end, created_at, updated_at
`

type CreateSubscriptionParams struct {
	FamilyID               string             `json:"family_id"`
	Provider               string             `json:"provider"`
	ProviderSubscriptionID string             `json:"provider_subscription_id"`
	Status                 SubscriptionStatus `json:"status"`
	Plan                   string             `json:"plan"`
	CurrentPeriodEnd       time.Time          `json:"current_period_end"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.FamilyID,
		arg.Provider,
		arg.ProviderSubscriptionID,
		arg.Status,
		arg.Plan,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Provider,
		&i.ProviderSubscriptionID,
		&i.Status,
		&i.Plan,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByFamilyID = `-- name: GetSubscriptionByFamilyID :one
SELECT id, family_id, provider, provider_subscription_id, status, plan, current_period_end, created_at, updated_at FROM subscriptions
WHERE family_id = $1 LIMIT 1
`

func (q *Queries) GetSubscriptionByFamilyID(ctx context.Context, familyID string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByFamilyID, familyID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Provider,
		&i.ProviderSubscriptionID,
		&i.Status,
		&i.Plan,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :one
UPDATE subscriptions
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, family_id, provider, provider_subscription_id, status, plan, current_period_end, created_at, updated_at
`

type UpdateSubscriptionStatusParams struct {
	ID     int64              `json:"id"`
	Status SubscriptionStatus `json:"status"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionStatus, arg.ID, arg.Status)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.FamilyID,
		&i.Provider,
		&i.ProviderSubscriptionID,
		&i.Status,
		&i.Plan,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
