// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: testing.sql

package db

import (
	"context"
)

const deleteAllWeeklySchedules = `-- name: DeleteAllWeeklySchedules :exec
DELETE FROM weekly_module_schedule
`

func (q *Queries) DeleteAllWeeklySchedules(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllWeeklySchedules)
	return err
}
