services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # headlamp-backend:
  #   build:
  #     context: ../../
  #     dockerfile: Dockerfile
  #   container_name: headlamp_backend_service
  #   restart: always
  #   env_file:
  #     - ./.env
  #   ports:
  #     - "8085:8080"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

volumes:
  postgres_data:
